/* esp32-firmware
 * Copyright (C) 2023 Erik Fleckstein <erik@tinkerforge.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <functional>

// Number of table rows that are requested from the table_lines_cb at once.
// Each call must return the next (up to) PDF_TABLE_LINES_PER_OBJECT rows.
#define PDF_TABLE_LINES_PER_OBJECT 8

#define PDF_INFO_MAX_ROWS 6
#define PDF_TILE_COUNT 3
#define PDF_SUBTOTAL_TABLES_MAX 2

// Cells of one row of a subtotal table
enum PDFSubtotalColumn {
    PDF_SUB_COL_NAME,
    PDF_SUB_COL_COUNT,
    PDF_SUB_COL_DURATION,
    PDF_SUB_COL_ENERGY,
    PDF_SUB_COL_COST, // Only if show_cost_column is set
    PDF_SUB_COL_COUNT_
};

// Upper bound for the length of all '\0'-terminated cells of one subtotal row
#define PDF_SUBTOTAL_ROW_LEN 160

struct PDFSubtotalTable {
    const char *title = "";
    const char *header = ""; // One cell per PDFSubtotalColumn. '\n' splits a header into two lines.
    uint32_t rows = 0;
};

// Cells of one charge as returned by table_lines_cb. The cost cell is only present if show_cost_column is set.
// Each charge is drawn as two lines: start/end, user/charger and meter start/end are stacked.
enum PDFTableColumn {
    PDF_COL_START,
    PDF_COL_END,
    PDF_COL_USER,
    PDF_COL_CHARGER,
    PDF_COL_DURATION,
    PDF_COL_METER_START,
    PDF_COL_METER_END,
    PDF_COL_ENERGY,
    PDF_COL_COST,
    PDF_COL_COUNT
};

enum PDFTableVisibleColumn {
    PDF_VCOL_NUMBER,    // consecutive number of the charge in this report, generated by the layout
    PDF_VCOL_TIME,      // start / end
    PDF_VCOL_NAMES,     // user / charger
    PDF_VCOL_DURATION,
    PDF_VCOL_METER,     // meter start / meter end
    PDF_VCOL_ENERGY,
    PDF_VCOL_COST,
    PDF_VCOL_COUNT
};

// All texts are UTF-8. Multi-cell texts are '\0'-separated.
struct PDFReport {
    const char *doc_title = "";
    const char *doc_author = "";
    const char *doc_subject = "";
    const char *doc_creator = "";
    const char *title = "";
    const char *subtitle = "";
    const char *period = "";

    const char *letterhead = "";
    int letterhead_lines = 0;

    const char *info_labels[PDF_INFO_MAX_ROWS] = {};
    const char *info_values[PDF_INFO_MAX_ROWS] = {};
    bool info_bold[PDF_INFO_MAX_ROWS] = {};
    int info_rows = 0;

    // Tile 0 spans the left column, tiles 1 and 2 share the right column.
    const char *tile_labels[PDF_TILE_COUNT] = {};
    const char *tile_values[PDF_TILE_COUNT] = {};

    const char *section_title = "";
    bool show_cost_column = false;
    const char *table_header = "";
    const char *no_charges_text = "";

    const char *totals_label = "";
    const char *totals_duration = "";
    const char *totals_energy = "";
    const char *totals_cost = "";

    // Tables with subtotals (e.g. per user), shown below the totals row
    PDFSubtotalTable subtotal_tables[PDF_SUBTOTAL_TABLES_MAX];
    int subtotal_table_count = 0;
    // Must write the '\0'-terminated cells (see PDFSubtotalColumn) of the given row to buf (PDF_SUBTOTAL_ROW_LEN bytes)
    std::function<void(int table, uint32_t row, char *buf)> subtotal_row;

    const char *note_title = "";
    const char *note = "";

    const char *footer = "";
    const char *page_label_format = "";
};

// table_lines_cb must return the next (up to) PDF_TABLE_LINES_PER_OBJECT rows, each consisting of one '\0'-terminated cell per PDFTableColumn.
int init_pdf_generator(std::function<int(const void *data, size_t len)> &write_callback,
                       const PDFReport &report,
                       uint32_t table_rows,
                       const std::function<int(const char **)> &table_lines_cb);
