version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/software/web"
    schedule:
      interval: "daily"
    groups:
      all-security:
        applies-to: "security-updates"
        patterns:
          - "*"
  - package-ecosystem: "us"
    directory: "/software"
    schedule:
      interval: "daily"
    groups:
      all-security:
        applies-to: "security-updates"
        patterns:
          - "*"
