version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/**"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
      all-security:
        applies-to: "security-updates"
        patterns:
          - "*"
