[Dependencies]
Requires = Io Scheduler
           Task Scheduler
           Event Log
           API

; Device enumeration must have run before our setup().
After = ESP32 Brick
        ESP32 Ethernet Brick
