table_prototypes = [
    ('Chisage ESS Hybrid Inverter', ['device_address', 'virtual_meter']),
]

default_device_addresses = [
    ('Chisage ESS Hybrid Inverter', 1),
]

specs = [
    {
        'name': 'Chisage ESS Hybrid Inverter',
        'virtual_meter': ('Chisage ESS Hybrid Inverter', 'Inverter'),
        'default_location': 'Inverter',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Inverter Voltage A [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 26,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Inverter Voltage B [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 27,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Inverter Voltage C [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 28,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Inverter Current A [0.01 A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 29,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Inverter Current B [0.01 A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 30,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Inverter Current C [0.01 A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 31,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Inverter Frequency [0.01 Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 52,
                'value_type': 'S16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Inverter Active Power A [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 65,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Inverter Active Power B [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 66,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Inverter Active Power C [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 67,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Inverter Reactive Power A [var]',
                'value_id': 'PowerReactiveL1IndCapDiff',
                'start_address': 68,
                'value_type': 'S16',
            },
            {
                'name': 'Inverter Reactive Power B [var]',
                'value_id': 'PowerReactiveL2IndCapDiff',
                'start_address': 69,
                'value_type': 'S16',
            },
            {
                'name': 'Inverter Reactive Power C [var]',
                'value_id': 'PowerReactiveL3IndCapDiff',
                'start_address': 70,
                'value_type': 'S16',
            },
        ],
    },
    {
        'name': 'Chisage ESS Hybrid Inverter Grid',
        'virtual_meter': ('Chisage ESS Hybrid Inverter', 'Grid'),
        'default_location': 'Grid',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Grid Voltage A [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 32,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage B [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 33,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage C [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 34,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current A [0.01 A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 35,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Grid Current B [0.01 A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 36,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Grid Current C [0.01 A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 37,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 53,
                'value_type': 'S16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Grid Active Power A [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 77,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Active Power B [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 78,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Active Power C [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 79,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Reactive Power A [var]',
                'value_id': 'PowerReactiveL1IndCapDiff',
                'start_address': 80,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Reactive Power B [var]',
                'value_id': 'PowerReactiveL2IndCapDiff',
                'start_address': 81,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Reactive Power C [var]',
                'value_id': 'PowerReactiveL3IndCapDiff',
                'start_address': 82,
                'value_type': 'S16',
            },
            {
                'name': 'Total Power Grid Purchase Electricity [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 2075,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Total Power Grid Sold Electricity [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 2078,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Chisage ESS Hybrid Inverter Battery',
        'virtual_meter': ('Chisage ESS Hybrid Inverter', 'Battery'),
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Battery Voltage [0.01 V]',
                'value_id': 'VoltageDC',
                'start_address': 2026,
                'value_type': 'S16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Battery Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 2027,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Battery Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 2036,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Battery SOC [%]',
                'value_id': 'StateOfCharge',
                'start_address': 2039,
                'value_type': 'U16',
            },
            {
                'name': 'Battery Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 2055,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Total Battery Charge [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 2069,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Total Battery Discharge [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 2072,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Chisage ESS Hybrid Inverter Load',
        'virtual_meter': ('Chisage ESS Hybrid Inverter', 'Load'),
        'default_location': 'Load',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Load Voltage A [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 38,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Load Voltage B [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 39,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Load Voltage C [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 40,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Load Current A [0.01 A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 41,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Load Current B [0.01 A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 42,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Load Current C [0.01 A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 43,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Load Active Power A [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 86,
                'value_type': 'S16',
            },
            {
                'name': 'Load Active Power B [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 87,
                'value_type': 'S16',
            },
            {
                'name': 'Load Active Power C [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 88,
                'value_type': 'S16',
            },
            {
                'name': 'Total Load Total Power Consumption [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 2081,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Chisage ESS Hybrid Inverter PV',
        'virtual_meter': ('Chisage ESS Hybrid Inverter', 'PV'),
        'default_location': 'PV',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'PV1 Voltage [0.1 V]',
                'value_id': 'VoltagePV1',
                'start_address': 2028,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Current [0.01 A]',
                'value_id': 'CurrentPV1Export',
                'start_address': 2029,
                'value_type': 'S16',
                'scale_factor': 0.01,
            },
            {
                'name': 'PV2 Voltage [0.1 V]',
                'value_id': 'VoltagePV2',
                'start_address': 2030,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Current [0.01 A]',
                'value_id': 'CurrentPV2Export',
                'start_address': 2031,
                'value_type': 'S16',
                'scale_factor': 0.01,
            },
            {
                'name': 'PV1 Power [W]',
                'value_id': 'PowerPV1Export',
                'start_address': 2037,
                'value_type': 'S16',
            },
            {
                'name': 'PV2 Power [W]',
                'value_id': 'PowerPV2Export',
                'start_address': 2038,
                'value_type': 'S16',
            },
            {
                'name': 'PV Average Voltage [0.1 V]',
                'value_id': 'VoltagePVAvg',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'PV Total Current [0.1 A]',
                'value_id': 'CurrentPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'PV Total Power [W]',
                'value_id': 'PowerPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Power Generation [0.1 kWh]',
                'value_id': 'EnergyPVSumExport',
                'start_address': 2066,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
]
