specs = [
    {
        'name': 'Eastron SDM630 TCP',
        'register_type': 'InputRegister',
        'start_address_offset': 1,
        'values': [
            {
                'name': 'Phase 1 line to neutral volts [V]',
                'value_id': 'VoltageL1N',
                'start_address': 1,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 line to neutral volts [V]',
                'value_id': 'VoltageL2N',
                'start_address': 3,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 line to neutral volts [V]',
                'value_id': 'VoltageL3N',
                'start_address': 5,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 current [A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 7,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 current [A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 9,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 current [A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 11,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 power [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 13,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 power [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 15,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 power [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 17,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 volt amps [VA]',
                'value_id': 'PowerApparentL1ImExSum',
                'start_address': 19,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 volt amps [VA]',
                'value_id': 'PowerApparentL2ImExSum',
                'start_address': 21,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 volt amps [VA]',
                'value_id': 'PowerApparentL3ImExSum',
                'start_address': 23,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 volt amps reactive [var]',
                'value_id': 'PowerReactiveL1IndCapDiff',
                'start_address': 25,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 volt amps reactive [var]',
                'value_id': 'PowerReactiveL2IndCapDiff',
                'start_address': 27,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 volt amps reactive [var]',
                'value_id': 'PowerReactiveL3IndCapDiff',
                'start_address': 29,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 power factor',
                'value_id': 'PowerFactorL1Directional',
                'start_address': 31,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 power factor',
                'value_id': 'PowerFactorL2Directional',
                'start_address': 33,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 power factor',
                'value_id': 'PowerFactorL3Directional',
                'start_address': 35,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 phase angle [°]',
                'value_id': 'PhaseAngleL1',
                'start_address': 37,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 phase angle [°]',
                'value_id': 'PhaseAngleL2',
                'start_address': 39,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 phase angle [°]',
                'value_id': 'PhaseAngleL3',
                'start_address': 41,
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to neutral volts [V]',
                'value_id': 'VoltageLNAvg',
                'start_address': 43,
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line current [A]',
                'value_id': 'CurrentLAvgImExSum',
                'start_address': 47,
                'value_type': 'F32BE',
            },
            {
                'name': 'Sum of line currents [A]',
                'value_id': 'CurrentLSumImExSum',
                'start_address': 49,
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system power [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 53,
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system volt amps [VA]',
                'value_id': 'PowerApparentLSumImExSum',
                'start_address': 57,
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system volt amps reactive [var]',
                'value_id': 'PowerReactiveLSumIndCapDiff',
                'start_address': 61,
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system power factor',
                'value_id': 'PowerFactorLSumDirectional',
                'start_address': 63,
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system phase angle [°]',
                'value_id': 'PhaseAngleLSum',
                'start_address': 67,
                'value_type': 'F32BE',
            },
            {
                'name': 'Frequency of supply voltages [Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 71,
                'value_type': 'F32BE',
            },
            {
                'name': 'Import Wh since last reset [kWh]',
                'value_id': 'EnergyActiveLSumImport', # FIXME: should be mapped resettable, but it's only resettable with an actual SDM630-TCP, not with a normal SDM630 behind an RS485/TCP converter
                'start_address': 73,
                'value_type': 'F32BE',
            },
            {
                'name': 'Export Wh since last reset [kWh]',
                'value_id': 'EnergyActiveLSumExport', # FIXME: should be mapped resettable, but it's only resettable with an actual SDM630-TCP, not with a normal SDM630 behind an RS485/TCP converter
                'start_address': 75,
                'value_type': 'F32BE',
            },
            {
                'name': 'Import VArh since last reset [kvarh]',
                'value_id': 'EnergyReactiveLSumInductive', # FIXME: should be mapped resettable, but it's only resettable with an actual SDM630-TCP, not with a normal SDM630 behind an RS485/TCP converter
                'start_address': 77,
                'value_type': 'F32BE',
            },
            {
                'name': 'Export VArh since last reset [kvarh]',
                'value_id': 'EnergyReactiveLSumCapacitive', # FIXME: should be mapped resettable, but it's only resettable with an actual SDM630-TCP, not with a normal SDM630 behind an RS485/TCP converter
                'start_address': 79,
                'value_type': 'F32BE',
            },
            {
                'name': 'VAh since last reset [kVAh]',
                'value_id': 'EnergyApparentLSumImExSum', # FIXME: should be mapped resettable, but it's only resettable with an actual SDM630-TCP, not with a normal SDM630 behind an RS485/TCP converter
                'start_address': 81,
                'value_type': 'F32BE',
            },
            {
                'name': 'Ah since last reset [Ah]',
                'value_id': 'ElectricCharge', # FIXME: should be mapped resettable, but it's only resettable with an actual SDM630-TCP, not with a normal SDM630 behind an RS485/TCP converter
                'start_address': 83,
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 1 to Line 2 volts [V]',
                'value_id': 'VoltageL1L2',
                'start_address': 201,
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 2 to Line 3 volts [V]',
                'value_id': 'VoltageL2L3',
                'start_address': 203,
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 3 to Line 1 volts [V]',
                'value_id': 'VoltageL3L1',
                'start_address': 205,
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to line volts [V]',
                'value_id': 'VoltageLLAvg',
                'start_address': 207,
                'value_type': 'F32BE',
            },
            {
                'name': 'Neutral current [A]',
                'value_id': 'CurrentNImExSum',
                'start_address': 225,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 L/N volts THD [%]',
                'value_id': 'VoltageTHDL1N',
                'start_address': 235,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 L/N volts THD [%]',
                'value_id': 'VoltageTHDL2N',
                'start_address': 237,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 L/N volts THD [%]',
                'value_id': 'VoltageTHDL3N',
                'start_address': 239,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 Current THD [%]',
                'value_id': 'CurrentTHDL1',
                'start_address': 241,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 Current THD [%]',
                'value_id': 'CurrentTHDL2',
                'start_address': 243,
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 Current THD [%]',
                'value_id': 'CurrentTHDL3',
                'start_address': 245,
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to neutral volts THD [%]',
                'value_id': 'VoltageTHDLNAvg',
                'start_address': 249,
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line current THD [%]',
                'value_id': 'CurrentTHDLAvg',
                'start_address': 251,
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 1 to line 2 volts THD [%]',
                'value_id': 'VoltageTHDL1L2',
                'start_address': 335,
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 2 to line 3 volts THD [%]',
                'value_id': 'VoltageTHDL2L3',
                'start_address': 337,
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 3 to line 1 volts THD [%]',
                'value_id': 'VoltageTHDL3L1',
                'start_address': 339,
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to line volts THD [%]',
                'value_id': 'VoltageTHDLLAvg',
                'start_address': 341,
                'value_type': 'F32BE',
            },
            {
                'name': 'Total kWh [kWh]',
                'value_id': 'EnergyActiveLSumImExSum',
                'start_address': 343,
                'value_type': 'F32BE',
            },
            {
                'name': 'Total kvarh [kvarh]',
                'value_id': 'EnergyReactiveLSumIndCapSum',
                'start_address': 345,
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 import kWh [kWh]',
                'value_id': 'EnergyActiveL1Import',
                'start_address': 347,
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 import kWh [kWh]',
                'value_id': 'EnergyActiveL2Import',
                'start_address': 349,
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 import kWh [kWh]',
                'value_id': 'EnergyActiveL3Import',
                'start_address': 351,
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 export kWh [kWh]',
                'value_id': 'EnergyActiveL1Export',
                'start_address': 353,
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 export kWh [kWh]',
                'value_id': 'EnergyActiveL2Export',
                'start_address': 355,
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 export kWh [kWh]',
                'value_id': 'EnergyActiveL3Export',
                'start_address': 357,
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 total kWh [kWh]',
                'value_id': 'EnergyActiveL1ImExSum',
                'start_address': 359,
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 total kWh [kWh]',
                'value_id': 'EnergyActiveL2ImExSum',
                'start_address': 361,
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 total kWh [kWh]',
                'value_id': 'EnergyActiveL3ImExSum',
                'start_address': 363,
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 import kvarh [kvarh]',
                'value_id': 'EnergyReactiveL1Inductive',
                'start_address': 365,
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 import kvarh [kvarh]',
                'value_id': 'EnergyReactiveL2Inductive',
                'start_address': 367,
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 import kvarh [kvarh]',
                'value_id': 'EnergyReactiveL3Inductive',
                'start_address': 369,
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 export kvarh [kvarh]',
                'value_id': 'EnergyReactiveL1Capacitive',
                'start_address': 371,
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 export kvarh [kvarh]',
                'value_id': 'EnergyReactiveL2Capacitive',
                'start_address': 373,
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 export kvarh [kvarh]',
                'value_id': 'EnergyReactiveL3Capacitive',
                'start_address': 375,
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 total kvarh [kvarh]',
                'value_id': 'EnergyReactiveL1IndCapSum',
                'start_address': 377,
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 total kvarh [kvarh]',
                'value_id': 'EnergyReactiveL2IndCapSum',
                'start_address': 379,
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 total kvarh [kvarh]',
                'value_id': 'EnergyReactiveL3IndCapSum',
                'start_address': 381,
                'value_type': 'F32BE',
            },
        ],
    },
]
