table_prototypes = [
    ('Fox ESS H3 AC3 Hybrid Inverter', ['device_address', 'virtual_meter']),
    ('Fox ESS H3 Smart Hybrid Inverter', ['device_address', 'virtual_meter']),
    ('Fox ESS H3 Pro Hybrid Inverter', ['device_address', 'virtual_meter']),
]

default_device_addresses = [
    ('Fox ESS H3 AC3 Hybrid Inverter', 247),
    ('Fox ESS H3 Smart Hybrid Inverter', 247),
    ('Fox ESS H3 Pro Hybrid Inverter', 247),
]

specs = [
    {
        'name': 'Fox ESS H3 AC3 Hybrid Inverter',
        'virtual_meter': ('Fox ESS H3 AC3 Hybrid Inverter', 'Inverter'),
        'default_location': 'Inverter',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Grid Voltage Phase R [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 31006,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage Phase S [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 31007,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage Phase T [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 31008,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current Phase R [0.1 A]',
                'value_id': 'CurrentL1ImExDiff',
                'start_address': 31009,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Grid Current Phase S [0.1 A]',
                'value_id': 'CurrentL2ImExDiff',
                'start_address': 31010,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Grid Current Phase T [0.1 A]',
                'value_id': 'CurrentL3ImExDiff',
                'start_address': 31011,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Grid Power Phase R [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 31012,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Grid Power Phase S [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 31013,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Grid Power Phase T [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 31014,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 31015,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Inverter Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 31032,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Yield Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 32015,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Fox ESS H3 AC3 Hybrid Inverter Grid',
        'virtual_meter': ('Fox ESS H3 AC3 Hybrid Inverter', 'Grid'),
        'default_location': 'Grid',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Smart Meter Export Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 32009,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Smart Meter Import Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 32012,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Smart Meter Power Phase R [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 31026,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Smart Meter Power Phase S [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 31027,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Smart Meter Power Phase T [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 31028,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
        ],
    },
    {
        'name': 'Fox ESS H3 AC3 Hybrid Inverter Battery',
        'virtual_meter': ('Fox ESS H3 AC3 Hybrid Inverter', 'Battery'),
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Battery Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 31034,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 31035,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Battery Discharge Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 31036,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Battery Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 31037,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery State Of Charge [%]',
                'value_id': 'StateOfCharge',
                'start_address': 31038,
                'value_type': 'U16',
            },
            {
                'name': 'Battery Charge Energy Total [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 32003,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery Discharge Energy Total [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 32006,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Fox ESS H3 AC3 Hybrid Inverter Load',
        'virtual_meter': ('Fox ESS H3 AC3 Hybrid Inverter', 'Load'),
        'default_location': 'Load',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Load Import Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 32021,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Load Power Phase R [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 31029,
                'value_type': 'S16',
            },
            {
                'name': 'Load Power Phase S [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 31030,
                'value_type': 'S16',
            },
            {
                'name': 'Load Power Phase T [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 31031,
                'value_type': 'S16',
            },
        ],
    },
    {
        'name': 'Fox ESS H3 AC3 Hybrid Inverter PV',
        'virtual_meter': ('Fox ESS H3 AC3 Hybrid Inverter', 'PV'),
        'default_location': 'PV',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Solar Energy Total [0.1 kWh]',
                'value_id': 'EnergyPVSumExport',
                'start_address': 32000,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Voltage [0.1 V]',
                'value_id': 'VoltagePV1',
                'start_address': 31000,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Current [0.1 A]',
                'value_id': 'CurrentPV1Export',
                'start_address': 31001,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Power [W]',
                'value_id': 'PowerPV1Export',
                'start_address': 31002,
                'value_type': 'U16',
            },
            {
                'name': 'PV2 Voltage [0.1 V]',
                'value_id': 'VoltagePV2',
                'start_address': 31003,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Current [0.1 A]',
                'value_id': 'CurrentPV2Export',
                'start_address': 31004,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Power [W]',
                'value_id': 'PowerPV2Export',
                'start_address': 31005,
                'value_type': 'U16',
            },
            {
                'name': 'PV Voltage Average [0.1 V]',
                'value_id': 'VoltagePVAvg',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'PV Current Total [0.1 A]',
                'value_id': 'CurrentPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'PV Power Total [W]',
                'value_id': 'PowerPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
        ],
    },
    {
        'name': 'Fox ESS H3 {variant} Hybrid Inverter',
        'virtual_meter': ('Fox ESS H3 {variant} Hybrid Inverter', 'Inverter'),
        'variants': ['Smart', 'Pro'],
        'default_location': 'Inverter',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Grid Voltage Phase R [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 39123,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage Phase S [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 39124,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage Phase T [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 39125,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current Phase R [0.001 A]',
                'value_id': 'CurrentL1ImExDiff',
                'start_address': 39126,
                'value_type': 'S32BE',
                'scale_factor': -0.001,
            },
            {
                'name': 'Grid Current Phase S [0.001 A]',
                'value_id': 'CurrentL2ImExDiff',
                'start_address': 39128,
                'value_type': 'S32BE',
                'scale_factor': -0.001,
            },
            {
                'name': 'Grid Current Phase T [0.001 A]',
                'value_id': 'CurrentL3ImExDiff',
                'start_address': 39130,
                'value_type': 'S32BE',
                'scale_factor': -0.001,
            },
            {
                'name': 'Grid Power Phase R [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 39248,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Grid Power Phase S [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 39250,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Grid Power Phase T [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 39252,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 39139,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Inverter Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 39141,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Yield Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 39621,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Yield Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 39621,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
        ],
    },
    {
        'name': 'Fox ESS H3 {variant} Hybrid Inverter Grid',
        'virtual_meter': ('Fox ESS H3 {variant} Hybrid Inverter', 'Grid'),
        'variants': ['Smart', 'Pro'],
        'default_location': 'Grid',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Smart Meter Export Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 39613,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Smart Meter Export Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 39613,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'Smart Meter Import Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 39617,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Smart Meter Import Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 39617,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'Smart Meter Power Phase R [0.1 W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 38816,
                'value_type': 'S32BE',
                'scale_factor': -0.1,
            },
            {
                'name': 'Smart Meter Power Phase S [0.1 W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 38818,
                'value_type': 'S32BE',
                'scale_factor': -0.1,
            },
            {
                'name': 'Smart Meter Power Phase T [0.1 W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 38820,
                'value_type': 'S32BE',
                'scale_factor': -0.1,
            },
        ],
    },
    {
        'name': 'Fox ESS H3 {variant} Hybrid Inverter Battery 1',
        'virtual_meter': ('Fox ESS H3 {variant} Hybrid Inverter', 'Battery 1'),
        'variants': ['Smart', 'Pro'],
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'BMS 1 Connection Status',
                'value_id': 'VALUE_ID_META',
                'start_address': 37002,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 1 Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 37609,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 37610,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 37611,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 SoC [%]',
                'value_id': 'StateOfCharge',
                'start_address': 37612,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 1 Design Energy [0.01 kWh]',
                'value_id': 'Capacity',
                'start_address': 37635,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Battery 1 Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 39230,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'BMS 2 Connection Status',
                'value_id': 'VALUE_ID_META',
                'start_address': 37700,
                'value_type': 'U16',
            },
            {
                'name': 'Total Charge Energy  [0.01 kWh]',  # this is the combined charge energy of both batteries, only show if battery 2 is offline
                'value_id': 'EnergyDCCharge',
                'start_address': 39605,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Total Charge Energy  [0.1 kWh]',  # this is the combined charge energy of both batteries, only show if battery 2 is offline
                'value_id': 'EnergyDCCharge',
                'start_address': 39605,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'Total Discharge Energy  [0.01 kWh]',  # this is the combined discharge energy of both batteries, only show if battery 2 is offline
                'value_id': 'EnergyDCDischarge',
                'start_address': 39609,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Total Discharge Energy  [0.1 kWh]',  # this is the combined discharge energy of both batteries, only show if battery 2 is offline
                'value_id': 'EnergyDCDischarge',
                'start_address': 39609,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
        ],
    },
    {
        'name': 'Fox ESS H3 {variant} Hybrid Inverter Battery 2',
        'virtual_meter': ('Fox ESS H3 {variant} Hybrid Inverter', 'Battery 2'),
        'variants': ['Smart', 'Pro'],
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'BMS 2 Connection Status',
                'value_id': 'VALUE_ID_META',
                'start_address': 37700,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 2 Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 38307,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 2 Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 38308,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 2 Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 38309,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 2 SoC [%]',
                'value_id': 'StateOfCharge',
                'start_address': 38310,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 2 Design Energy [0.01 kWh]',
                'value_id': 'Capacity',
                'start_address': 38333,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Battery 2 Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 39235,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'BMS 1 Connection Status',
                'value_id': 'VALUE_ID_META',
                'start_address': 37002,
                'value_type': 'U16',
            },
            {
                'name': 'Total Charge Energy  [0.01 kWh]',  # this is the combined charge energy of both batteries, only show if battery 1 is offline
                'value_id': 'EnergyDCCharge',
                'start_address': 39605,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Total Charge Energy  [0.1 kWh]',  # this is the combined charge energy of both batteries, only show if battery 1 is offline
                'value_id': 'EnergyDCCharge',
                'start_address': 39605,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'Total Discharge Energy  [0.01 kWh]',  # this is the combined discharge energy of both batteries, only show if battery 1 is offline
                'value_id': 'EnergyDCDischarge',
                'start_address': 39609,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Total Discharge Energy  [0.1 kWh]',  # this is the combined discharge energy of both batteries, only show if battery 1 is offline
                'value_id': 'EnergyDCDischarge',
                'start_address': 39609,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
        ],
    },
    {
        'name': 'Fox ESS H3 {variant} Hybrid Inverter Battery 1 And 2',
        'virtual_meter': ('Fox ESS H3 {variant} Hybrid Inverter', 'Battery 1 And 2'),
        'variants': ['Smart', 'Pro'],
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'BMS 1 Connection Status',
                'value_id': 'VALUE_ID_META',
                'start_address': 37002,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 1 Voltage [0.1 V]',
                'value_id': 'VALUE_ID_META',
                'start_address': 37609,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 Current [0.1 A]',
                'value_id': 'VALUE_ID_META',
                'start_address': 37610,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 Temperature [0.1 °C]',
                'value_id': 'VALUE_ID_META',
                'start_address': 37611,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 SoC [%]',
                'value_id': 'VALUE_ID_META',
                'start_address': 37612,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 1 Design Energy [0.01 kWh]',
                'value_id': 'VALUE_ID_META',
                'start_address': 37635,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'BMS 2 Connection Status',
                'value_id': 'VALUE_ID_META',
                'start_address': 37700,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 2 Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 38307,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 2 Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 38308,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 2 Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 38309,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 2 SoC [%]',
                'value_id': 'StateOfCharge',
                'start_address': 38310,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 2 Design Energy [0.01 kWh]',
                'value_id': 'Capacity',
                'start_address': 38333,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Battery Combined Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 39237,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Total Charge Energy  [0.01 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 39605,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Total Charge Energy  [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 39605,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'Total Discharge Energy  [0.01 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 39609,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Total Discharge Energy  [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 39609,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
        ],
    },
    {
        'name': 'Fox ESS H3 {variant} Hybrid Inverter Load',
        'virtual_meter': ('Fox ESS H3 {variant} Hybrid Inverter', 'Load'),
        'variants': ['Smart', 'Pro'],
        'default_location': 'Load',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Load Import Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 39629,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Load Import Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 39629,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'Load Power Phase R [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 39219,
                'value_type': 'S32BE',
            },
            {
                'name': 'Load Power Phase S [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 39221,
                'value_type': 'S32BE',
            },
            {
                'name': 'Load Power Phase T [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 39223,
                'value_type': 'S32BE',
            },
            {
                'name': 'Load Combined Power [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 39225,
                'value_type': 'S32BE',
            },
        ],
    },
    {
        'name': 'Fox ESS H3 {variant} Hybrid Inverter PV',
        'virtual_meter': ('Fox ESS H3 {variant} Hybrid Inverter', 'PV'),
        'variants': ['Smart', 'Pro'],
        'default_location': 'PV',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Solar Energy Total [0.1 kWh]',
                'value_id': 'EnergyPVSumExport',
                'start_address': 39601,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
                'variants': ['Smart'],
            },
            {
                'name': 'Solar Energy Total [0.1 kWh]',
                'value_id': 'EnergyPVSumExport',
                'start_address': 39601,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'PV1 Voltage [0.1 V]',
                'value_id': 'VoltagePV1',
                'start_address': 39070,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Current [0.01 A]',
                'value_id': 'CurrentPV1Export',
                'start_address': 39071,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'PV1 Power [W]',
                'value_id': 'PowerPV1Export',
                'start_address': 39279,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV2 Voltage [0.1 V]',
                'value_id': 'VoltagePV2',
                'start_address': 39072,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Current [0.01 A]',
                'value_id': 'CurrentPV2Export',
                'start_address': 39073,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'PV2 Power [W]',
                'value_id': 'PowerPV2Export',
                'start_address': 39281,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV3 Voltage [0.1 V]',
                'value_id': 'VoltagePV3',
                'start_address': 39074,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV3 Current [0.01 A]',
                'value_id': 'CurrentPV3Export',
                'start_address': 39075,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'PV3 Power [W]',
                'value_id': 'PowerPV3Export',
                'start_address': 39283,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV4 Voltage [0.1 V]',
                'value_id': 'VoltagePV4',
                'start_address': 39076,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV4 Current [0.01 A]',
                'value_id': 'CurrentPV4Export',
                'start_address': 39077,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'PV4 Power [W]',
                'value_id': 'PowerPV4Export',
                'start_address': 39285,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV5 Voltage [0.1 V]',
                'value_id': 'VoltagePV5',
                'start_address': 39078,
                'value_type': 'U16',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'PV5 Current [0.01 A]',
                'value_id': 'CurrentPV5Export',
                'start_address': 39079,
                'value_type': 'U16',
                'scale_factor': 0.01,
                'variants': ['Pro'],
            },
            {
                'name': 'PV5 Power [W]',
                'value_id': 'PowerPV5Export',
                'start_address': 39287,
                'value_type': 'U32BE',
                'variants': ['Pro'],
            },
            {
                'name': 'PV6 Voltage [0.1 V]',
                'value_id': 'VoltagePV6',
                'start_address': 39080,
                'value_type': 'U16',
                'scale_factor': 0.1,
                'variants': ['Pro'],
            },
            {
                'name': 'PV6 Current [0.01 A]',
                'value_id': 'CurrentPV6Export',
                'start_address': 39081,
                'value_type': 'U16',
                'scale_factor': 0.01,
                'variants': ['Pro'],
            },
            {
                'name': 'PV6 Power [W]',
                'value_id': 'PowerPV6Export',
                'start_address': 39289,
                'value_type': 'U32BE',
                'variants': ['Pro'],
            },
            {
                'name': 'PV Voltage Average [0.1 V]',
                'value_id': 'VoltagePVAvg',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'PV Current Total [0.01 A]',
                'value_id': 'CurrentPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'PV Power Total [W]',
                'value_id': 'PowerPVSumExport',
                'start_address': 39118,
                'value_type': 'U32BE',
            },
        ],
    },
]
