specs = [
    {
        'name': 'Fox ESS H3 Hybrid Inverter',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Grid Voltage Phase R [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 31006,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage Phase S [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 31007,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage Phase T [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 31008,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current Phase R [0.1 A]',
                'value_id': 'CurrentL1ImExDiff',
                'start_address': 31009,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current Phase S [0.1 A]',
                'value_id': 'CurrentL2ImExDiff',
                'start_address': 31010,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current Phase T [0.1 A]',
                'value_id': 'CurrentL3ImExDiff',
                'start_address': 31011,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Power Phase R [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 31012,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Power Phase S [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 31013,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Power Phase T [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 31014,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 31015,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Inverter Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 31032,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Fox ESS H3 Hybrid Inverter Grid',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Smart Meter Import Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 32012,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Smart Meter Export Total [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 32015,
                'value_type': 'U32BE',
                'scale_factor': 0.01,
            },
            {
                'name': 'Smart Meter Power Phase R [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 31026,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Smart Meter Power Phase S [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 31027,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Smart Meter Power Phase T [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 31028,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
        ],
    },
    {
        'name': 'Fox ESS H3 Hybrid Inverter Battery',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'Battery Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 31034,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 31035,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Battery Discharge Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 31036,
                'value_type': 'S16',
                'scale_factor': -1.0,
            },
            {
                'name': 'Battery Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 31037,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery State Of Charge [%]',
                'value_id': 'StateOfCharge',
                'start_address': 31038,
                'value_type': 'U16',
            },
            {
                'name': 'Battery Discharge Energy Total [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 32003,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery Charge Energy Total [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 32006,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
]
