table_prototypes = [
    ('Goodwe Hybrid Inverter', ['device_address', 'virtual_meter']),
]

default_device_addresses = [
    ('Goodwe Hybrid Inverter', 247),
]

specs = [
    {
        'name': 'Goodwe Hybrid Inverter',
        'virtual_meter': ('Goodwe Hybrid Inverter', 'Inverter'),
        'default_location': 'Inverter',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Total Power of Inverter [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 35137,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Inverter Internal Temperature [0.1 °C]',
                'value_id': 'TemperatureCabinet',
                'start_address': 35174,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Radiator Temperature [0.1 °C]',
                'value_id': 'TemperatureHeatSink',
                'start_address': 35176,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Total Feed Energy to Grid [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 35195,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Total Draw Energy from Grid [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 35200,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Grid',
        'virtual_meter': ('Goodwe Hybrid Inverter', 'Grid'),
        'default_location': 'Grid',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'R Phase Grid Voltage [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 35121,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'R Phase Grid Current [0.1 A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 35122,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'R Phase Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyL1',
                'start_address': 35123,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'R Phase Grid Power [W]',  # FIXME: this value matches voltage times current, but seems to be too big compared to the total
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 35124,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'S Phase Grid Voltage [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 35126,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'S Phase Grid Current [0.1 A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 35127,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'S Phase Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyL2',
                'start_address': 35128,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'S Phase Grid Power [W]',  # FIXME: this value matches voltage times current, but seems to be too big compared to the total
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 35129,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'T Phase Grid Voltage [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 35131,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'T Phase Grid Current [0.1 A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 35132,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'T Phase Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyL3',
                'start_address': 35133,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'T Phase Grid Power [W]',  # FIXME: this value matches voltage times current, but seems to be too big compared to the total
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 35134,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'AC Active Power [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 35139,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'AC Reactive Power [var]',
                'value_id': 'PowerReactiveLSumIndCapDiff',
                'start_address': 35141,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'AC Apparent Power [VA]',
                'value_id': 'PowerApparentLSumImExDiff',
                'start_address': 35143,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Active Energy Total Sell [0.01 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 36104,
                'value_type': 'U64BE',
                'scale_factor': 0.01,
            },
            {
                'name': 'Active Energy Total Buy [0.01 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 36120,
                'value_type': 'U64BE',
                'scale_factor': 0.01,
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Battery Modes',
        'virtual_meter': ('Goodwe Hybrid Inverter', 'Battery'),
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Battery 1 Mode',
                'value_id': 'VALUE_ID_META',
                'start_address': 35184,
                'value_type': 'U16',
            },
            {
                # Reading "BMS 2 Pack Temperature" (39001) and "Battery 2 Capacity" (39005) when "Battery 2 Mode" is 0,
                # might result in constant timeouts, blocking the whole reading process
                'name': 'Battery 2 Mode',
                'value_id': 'VALUE_ID_META',
                'start_address': 35266,
                'value_type': 'U16',
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Battery 1',
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Battery 1 Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 35180,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 1 Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 35181,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Battery 1 Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 35182,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Charge Energy [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 35206,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Discharge Energy [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 35209,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 Pack Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 37003,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 1 Capacity [%]',
                'value_id': 'StateOfCharge',
                'start_address': 37007,
                'value_type': 'U16',
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Battery 2',
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Battery 2 Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 35262,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 2 Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 35263,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Battery 2 Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 35264,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Charge Energy [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 35206,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Discharge Energy [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 35209,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 2 Pack Temperature [0.1 °C]',
                'value_id': 'Temperature',
                'start_address': 39001,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 2 Capacity [%]',
                'value_id': 'StateOfCharge',
                'start_address': 39005,
                'value_type': 'U16',
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Battery 1 And 2',
        'default_location': 'Battery',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'Battery 1 Voltage [0.1 V]',
                'value_id': 'VALUE_ID_META',
                'start_address': 35180,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 1 Current [0.1 A]',
                'value_id': 'VALUE_ID_META',
                'start_address': 35181,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Battery 1 Power [W]',
                'value_id': 'VALUE_ID_META',
                'start_address': 35182,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Battery 2 Voltage [0.1 V]',
                'value_id': 'VALUE_ID_META',
                'start_address': 35262,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 2 Current [0.1 A]',
                'value_id': 'VALUE_ID_META',
                'start_address': 35263,
                'value_type': 'S16',
                'scale_factor': -0.1,
            },
            {
                'name': 'Battery 2 Power [W]',
                'value_id': 'VALUE_ID_META',
                'start_address': 35264,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Charge Energy [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 35206,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Discharge Energy [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 35209,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'BMS 1 Pack Temperature [0.1 °C]',
                'value_id': 'VALUE_ID_META',
                'start_address': 37003,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 1 Capacity [%]',
                'value_id': 'VALUE_ID_META',
                'start_address': 37007,
                'value_type': 'U16',
            },
            {
                'name': 'BMS 2 Pack Temperature [0.1 °C]',
                'value_id': 'VALUE_ID_META',
                'start_address': 39001,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery 2 Capacity [%]',
                'value_id': 'VALUE_ID_META',
                'start_address': 39005,
                'value_type': 'U16',
            },
            {
                'name': 'Battery Voltage Avg [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Battery Current Sum [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Battery Power Sum [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'BMS Pack Temperature Avg [°C]',
                'value_id': 'Temperature',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Battery Capacity Avg [%]',
                'value_id': 'StateOfCharge',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Load',
        'virtual_meter': ('Goodwe Hybrid Inverter', 'Load'),
        'default_location': 'Load',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'R Phase Load Power [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 35163,
                'value_type': 'S32BE',
            },
            {
                'name': 'S Phase Load Power [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 35165,
                'value_type': 'S32BE',
            },
            {
                'name': 'T Phase Load Power [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 35167,
                'value_type': 'S32BE',
            },
            {
                'name': 'Total Load Power [W]',  # FIXME: this seems to be less than the sum of the RST phase load powers
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 35171,
                'value_type': 'S32BE',
            },
            {
                'name': 'Total Energy of Load [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 35203,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Backup Load',
        'virtual_meter': ('Goodwe Hybrid Inverter', 'Backup Load'),
        'default_location': 'Load',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'R Phase Load Voltage of Backup [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 35145,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'R Phase Load Current of Backup [0.1 A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 35146,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'R Phase Load Frequency of Backup [0.01 Hz]',
                'value_id': 'FrequencyL1',
                'start_address': 35147,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'R Phase Load Power of Backup [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 35149,
                'value_type': 'S32BE',
            },
            {
                'name': 'S Phase Load Voltage of Backup [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 35151,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'S Phase Load Current of Backup [0.1 A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 35152,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'S Phase Load Frequency of Backup [0.01 Hz]',
                'value_id': 'FrequencyL2',
                'start_address': 35153,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'S Phase Load Power of Backup [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 35155,
                'value_type': 'S32BE',
            },
            {
                'name': 'T Phase Load Voltage of Backup [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 35157,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'T Phase Load Current of Backup [0.1 A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 35158,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'T Phase Load Frequency of Backup [0.01 Hz]',
                'value_id': 'FrequencyL3',
                'start_address': 35159,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'T Phase Load Power of Backup [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 35161,
                'value_type': 'S32BE',
            },
            {
                'name': 'Total Load Power of Backup [W]',  # FIXME: this seems to be less than the sum of the RST phase load powers
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 35169,
                'value_type': 'S32BE',
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter Meter',
        'virtual_meter': ('Goodwe Hybrid Inverter', 'Meter'),
        'default_location': 'Other',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'R Phase Active Power [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 36005,  # FIXME: use 36019 as S32BE for ARM version > 09
                'value_type': 'S16',
            },
            {
                'name': 'S Phase Active Power [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 36006,  # FIXME: use 36021 as S32BE for ARM version > 09
                'value_type': 'S16',
            },
            {
                'name': 'T Phase Active Power [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 36007,  # FIXME: use 36023 as S32BE for ARM version > 09
                'value_type': 'S16',
            },
            {
                'name': 'Total Active Power [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 36008,  # FIXME: use 36025 as S32BE for ARM version > 09
                'value_type': 'S16',
            },
            {
                'name': 'Total Reactive Power [W]',
                'value_id': 'PowerReactiveLSumIndCapDiff',
                'start_address': 36009,  # FIXME: use 36033 as S32BE for ARM version > 09
                'value_type': 'S16',
            },
            {
                'name': 'R Phase Power Factor [0.001]',
                'value_id': 'PowerFactorL1',
                'start_address': 36010,
                'value_type': 'S16',
                'scale_factor': 0.001,
            },
            {
                'name': 'S Phase Power Factor [0.001]',
                'value_id': 'PowerFactorL2',
                'start_address': 36011,
                'value_type': 'S16',
                'scale_factor': 0.001,
            },
            {
                'name': 'T Phase Power Factor [0.001]',
                'value_id': 'PowerFactorL3',
                'start_address': 36012,
                'value_type': 'S16',
                'scale_factor': 0.001,
            },
            {
                'name': 'Total Power Factor [0.001]',
                'value_id': 'PowerFactorLSum',
                'start_address': 36013,
                'value_type': 'S16',
                'scale_factor': 0.001,
            },
            {
                'name': 'Frequency [0.01 Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 36014,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Total Feed Energy to Grid [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 36015,
                'value_type': 'F32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Total Draw Energy from Grid [0.1 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 36017,
                'value_type': 'F32BE',
                'scale_factor': 0.1,
            },
            {
                'name': 'R Phase Active Power S32 [W]',
                #'value_id': 'PowerActiveL1ImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36019,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'S Phase Active Power S32 [W]',
                #'value_id': 'PowerActiveL2ImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36021,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'T Phase Active Power S32 [W]',
                #'value_id': 'PowerActiveL3ImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36023,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Total Active Power S32 [W]',
                #'value_id': 'PowerActiveLSumImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36025,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'R Phase Reactive Power S32 [W]',
                #'value_id': 'PowerReactiveL1IndCapDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36027,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'S Phase Reactive Power S32 [var]',
                #'value_id': 'PowerReactiveL2IndCapDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36029,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'T Phase Reactive Power S32 [var]',
                #'value_id': 'PowerReactiveL3IndCapDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36031,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Total Reactive Power S32 [var]',
                #'value_id': 'PowerReactiveLSumIndCapDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36033,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'R Phase Apparent Power S32 [VA]',
                #'value_id': 'PowerApparentL1ImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36035,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'S Phase Apparent Power S32 [VA]',
                #'value_id': 'PowerApparentL2ImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36037,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'T Phase Apparent Power S32 [VA]',
                #'value_id': 'PowerApparentL3ImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36039,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Total Apparent Power S32 [VA]',
                #'value_id': 'PowerApparentLSumImExDiff',
                'value_id': 'VALUE_ID_DEBUG',
                'start_address': 36041,
                'value_type': 'S32BE',
                'scale_factor': -1.0,
            },
        ],
    },
    {
        'name': 'Goodwe Hybrid Inverter PV',
        'virtual_meter': ('Goodwe Hybrid Inverter', 'PV'),
        'default_location': 'PV',
        'register_type': 'HoldingRegister',
        'values': [
            {
                'name': 'PV Mode',
                'value_id': 'VALUE_ID_META',
                'start_address': 35119,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV1 Voltage [0.1 V]',
                'value_id': 'VoltagePV1',
                'start_address': 35103,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Current [0.1 A]',
                'value_id': 'CurrentPV1Export',
                'start_address': 35104,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Power [W]',
                'value_id': 'PowerPV1Export',
                'start_address': 35105,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV2 Voltage [0.1 V]',
                'value_id': 'VoltagePV2',
                'start_address': 35107,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Current [0.1 A]',
                'value_id': 'CurrentPV2Export',
                'start_address': 35108,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Power [W]',
                'value_id': 'PowerPV2Export',
                'start_address': 35109,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV3 Voltage [0.1 V]',
                'value_id': 'VoltagePV3',
                'start_address': 35111,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV3 Current [0.1 A]',
                'value_id': 'CurrentPV3Export',
                'start_address': 35112,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV3 Power [W]',
                'value_id': 'PowerPV3Export',
                'start_address': 35113,
                'value_type': 'U32BE',
            },
            {
                'name': 'PV4 Voltage [0.1 V]',
                'value_id': 'VoltagePV4',
                'start_address': 35115,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV4 Current [0.1 A]',
                'value_id': 'CurrentPV4Export',
                'start_address': 35116,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV4 Power [W]',
                'value_id': 'PowerPV4Export',
                'start_address': 35117,
                'value_type': 'U32BE',
            },
            {
                'name': 'Average PV Voltage [0.1 V]',
                'value_id': 'VoltagePVAvg',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Current [0.1 A]',
                'value_id': 'CurrentPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Power [W]',
                'value_id': 'PowerPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Energy [0.1 kWh]',
                'value_id': 'EnergyPVSumExport',
                'start_address': 35191,
                'value_type': 'U32BE',
                'scale_factor': 0.1,
            },
        ],
    },
]
