table_prototypes = [
    ('Janitza', ['device_address']),
]

default_device_addresses = [
    ('Janitza', 1),
]

specs = [
    {
        'name': 'Janitza',
        'default_location': 'Unknown',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'Voltage L1-N [V]',
                'value_id': 'VoltageL1N',
                'start_address': 19000,
                'value_type': 'F32BE',
            },
            {
                'name': 'Voltage L2-N [V]',
                'value_id': 'VoltageL2N',
                'start_address': 19002,
                'value_type': 'F32BE',
            },
            {
                'name': 'Voltage L3-N [V]',
                'value_id': 'VoltageL3N',
                'start_address': 19004,
                'value_type': 'F32BE',
            },
            {
                'name': 'Voltage L1-L2 [V]',
                'value_id': 'VoltageL1L2',
                'start_address': 19006,
                'value_type': 'F32BE',
            },
            {
                'name': 'Voltage L2-L3 [V]',
                'value_id': 'VoltageL2L3',
                'start_address': 19008,
                'value_type': 'F32BE',
            },
            {
                'name': 'Voltage L3-L1 [V]',
                'value_id': 'VoltageL3L1',
                'start_address': 19010,
                'value_type': 'F32BE',
            },
            {
                'name': 'Current L1 [A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 19012,
                'value_type': 'F32BE',
            },
            {
                'name': 'Current L2 [A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 19014,
                'value_type': 'F32BE',
            },
            {
                'name': 'Current L3 [A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 19016,
                'value_type': 'F32BE',
            },
            {
                'name': 'Current L1+L2+L3 [A]',
                'value_id': 'CurrentLSumImExSum',
                'start_address': 19018,
                'value_type': 'F32BE',
            },
            {
                'name': 'Real power L1 [W]',
                'value_id': 'PowerActiveL1ImExDiff',  # FIXME: sign?
                'start_address': 19020,
                'value_type': 'F32BE',
            },
            {
                'name': 'Real power L2 [W]',
                'value_id': 'PowerActiveL2ImExDiff',  # FIXME: sign?
                'start_address': 19022,
                'value_type': 'F32BE',
            },
            {
                'name': 'Real power L3 [W]',
                'value_id': 'PowerActiveL3ImExDiff',  # FIXME: sign?
                'start_address': 19024,
                'value_type': 'F32BE',
            },
            {
                'name': 'Real power L1+L2+L3 [W]',
                'value_id': 'PowerActiveLSumImExDiff',  # FIXME: sign?
                'start_address': 19026,
                'value_type': 'F32BE',
            },
            {
                'name': 'Apparent power L1 [VA]',
                'value_id': 'PowerApparentL1ImExSum',
                'start_address': 19028,
                'value_type': 'F32BE',
            },
            {
                'name': 'Apparent power L2 [VA]',
                'value_id': 'PowerApparentL2ImExSum',
                'start_address': 19030,
                'value_type': 'F32BE',
            },
            {
                'name': 'Apparent power L3 [VA]',
                'value_id': 'PowerApparentL3ImExSum',
                'start_address': 19032,
                'value_type': 'F32BE',
            },
            {
                'name': 'Apparent power L1+L2+L3 [VA]',
                'value_id': 'PowerApparentLSumImExSum',
                'start_address': 19034,
                'value_type': 'F32BE',
            },
            {
                'name': 'Reactive power L1 [var]',
                'value_id': 'PowerReactiveL1IndCapDiff',  # FIXME: sign?
                'start_address': 19036,
                'value_type': 'F32BE',
            },
            {
                'name': 'Reactive power L2 [var]',
                'value_id': 'PowerReactiveL2IndCapDiff',  # FIXME: sign?
                'start_address': 19038,
                'value_type': 'F32BE',
            },
            {
                'name': 'Reactive power L3 [var]',
                'value_id': 'PowerReactiveL3IndCapDiff',  # FIXME: sign?
                'start_address': 19040,
                'value_type': 'F32BE',
            },
            {
                'name': 'Reactive power L1+L2+L3 [var]',
                'value_id': 'PowerReactiveLSumIndCapDiff',  # FIXME: sign?
                'start_address': 19042,
                'value_type': 'F32BE',
            },
            {
                'name': 'Power factor L1',
                'value_id': 'PowerFactorL1',
                'start_address': 19044,
                'value_type': 'F32BE',
            },
            {
                'name': 'Power factor L2',
                'value_id': 'PowerFactorL2',
                'start_address': 19046,
                'value_type': 'F32BE',
            },
            {
                'name': 'Power factor L3',
                'value_id': 'PowerFactorL3',
                'start_address': 19048,
                'value_type': 'F32BE',
            },
            {
                'name': 'Frequency [Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 19050,
                'value_type': 'F32BE',
            },
            {
                'name': 'Real energy L1 [Wh]',
                'value_id': 'EnergyActiveL1ImExDiff',
                'start_address': 19054,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L2 [Wh]',
                'value_id': 'EnergyActiveL2ImExDiff',
                'start_address': 19056,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L3 [Wh]',
                'value_id': 'EnergyActiveL3ImExDiff',
                'start_address': 19058,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L1+L2+L3 [Wh]',
                'value_id': 'EnergyActiveLSumImExDiff',
                'start_address': 19060,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L1, consumed [Wh]',
                'value_id': 'EnergyActiveL1Import',
                'start_address': 19062,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L2, consumed [Wh]',
                'value_id': 'EnergyActiveL2Import',
                'start_address': 19064,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L3, consumed [Wh]',
                'value_id': 'EnergyActiveL3Import',
                'start_address': 19066,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L1+L2+L3, consumed [Wh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 19068,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L1, delivered [Wh]',
                'value_id': 'EnergyActiveL1Export',
                'start_address': 19070,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L2, delivered [Wh]',
                'value_id': 'EnergyActiveL2Export',
                'start_address': 19072,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L3, delivered [Wh]',
                'value_id': 'EnergyActiveL3Export',
                'start_address': 19074,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Real energy L1+L2+L3, delivered [Wh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 19076,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Apparent energy L1 [VAh]',
                'value_id': 'EnergyApparentL1ImExSum',
                'start_address': 19078,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Apparent energy L2 [VAh]',
                'value_id': 'EnergyApparentL2ImExSum',
                'start_address': 19080,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Apparent energy L3 [VAh]',
                'value_id': 'EnergyApparentL3ImExSum',
                'start_address': 19082,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Apparent energy L1+L2+L3 [VAh]',
                'value_id': 'EnergyApparentLSumImExSum',
                'start_address': 19084,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L1 [varh]',
                'value_id': 'EnergyReactiveL1IndCapDiff',
                'start_address': 19086,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L2 [varh]',
                'value_id': 'EnergyReactiveL2IndCapDiff',
                'start_address': 19088,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L3 [varh]',
                'value_id': 'EnergyReactiveL3IndCapDiff',
                'start_address': 19090,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L1+L2+L3 [varh]',
                'value_id': 'EnergyReactiveLSumIndCapDiff',
                'start_address': 19092,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L1, inductive [varh]',
                'value_id': 'EnergyReactiveL1Inductive',
                'start_address': 19094,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L2, inductive [varh]',
                'value_id': 'EnergyReactiveL2Inductive',
                'start_address': 19096,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L3, inductive [varh]',
                'value_id': 'EnergyReactiveL3Inductive',
                'start_address': 19098,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L1+L2+L3, inductive [varh]',
                'value_id': 'EnergyReactiveLSumInductive',
                'start_address': 19100,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L1, capacitive [varh]',
                'value_id': 'EnergyReactiveL1Capacitive',
                'start_address': 19102,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L2, capacitive [varh]',
                'value_id': 'EnergyReactiveL2Capacitive',
                'start_address': 19104,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L3, capacitive [varh]',
                'value_id': 'EnergyReactiveL3Capacitive',
                'start_address': 19106,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Reactive energy L1+L2+L3, capacitive [varh]',
                'value_id': 'EnergyReactiveLSumCapacitive',
                'start_address': 19108,
                'value_type': 'F32BE',
                'scale_factor': 0.001,
            },
            {
                'name': 'Voltage THD L1-N [%]',
                'value_id': 'VoltageTHDL1N',
                'start_address': 19110,
                'value_type': 'F32BE',
            },
            {
                'name': 'Voltage THD L2-N [%]',
                'value_id': 'VoltageTHDL2N',
                'start_address': 19112,
                'value_type': 'F32BE',
            },
            {
                'name': 'Voltage THD L3-N [%]',
                'value_id': 'VoltageTHDL3N',
                'start_address': 19114,
                'value_type': 'F32BE',
            },
            {
                'name': 'Current THD L1 [%]',
                'value_id': 'CurrentTHDL1',
                'start_address': 19116,
                'value_type': 'F32BE',
            },
            {
                'name': 'Current THD L2 [%]',
                'value_id': 'CurrentTHDL2',
                'start_address': 19118,
                'value_type': 'F32BE',
            },
            {
                'name': 'Current THD L3 [%]',
                'value_id': 'CurrentTHDL3',
                'start_address': 19120,
                'value_type': 'F32BE',
            },
        ],
    },
]
