table_prototypes = [
    ('Solax Hybrid Inverter', ['device_address', 'virtual_meter']),
    ('Solax String Inverter', ['device_address', 'virtual_meter']),
]

default_device_addresses = [
    ('Solax Hybrid Inverter', 1),
    ('Solax String Inverter', 1),
]

specs = [
    {
        'name': 'Solax Hybrid Inverter',
        'virtual_meter': ('Solax Hybrid Inverter', 'Inverter'),
        'default_location': 'Inverter',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'Energy Total To Grid [0.1 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 0x52,
                'value_type': 'U32LE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Solax Hybrid Inverter Grid',
        'virtual_meter': ('Solax Hybrid Inverter', 'Grid'),
        'default_location': 'Grid',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'Feedin Power [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 0x46,
                'value_type': 'S32LE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Feedin Energy Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 0x48,
                'value_type': 'U32LE',
                'scale_factor': 0.01,
            },
            {
                'name': 'Consume Energy Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 0x4A,
                'value_type': 'U32LE',
                'scale_factor': 0.01,
            },
            {
                'name': 'Grid Reactive Power Total Meter [var]',
                'value_id': 'PowerReactiveLSumIndCapDiff',  # FIXME: direction?
                'start_address': 0xC0,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Reactive Power R Meter [var]',
                'value_id': 'PowerReactiveL1IndCapDiff',  # FIXME: direction?
                'start_address': 0xC1,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Reactive Power S Meter [var]',
                'value_id': 'PowerReactiveL2IndCapDiff',  # FIXME: direction?
                'start_address': 0xC2,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Reactive Power T Meter [var]',
                'value_id': 'PowerReactiveL3IndCapDiff',  # FIXME: direction?
                'start_address': 0xC3,
                'value_type': 'S16',
            },
            {
                'name': 'Grid Power Factor Total Meter [0.01]',
                'value_id': 'PowerFactorLSumDirectional',
                'start_address': 0xC4,
                'value_type': 'S16',
                'scale_factor': -0.01,
            },
            {
                'name': 'Grid Power Factor R Meter [0.01]',
                'value_id': 'PowerFactorL1Directional',
                'start_address': 0xC5,
                'value_type': 'S16',
                'scale_factor': -0.01,
            },
            {
                'name': 'Grid Power Factor S Meter [0.01]',
                'value_id': 'PowerFactorL2Directional',
                'start_address': 0xC6,
                'value_type': 'S16',
                'scale_factor': -0.01,
            },
            {
                'name': 'Grid Power Factor T Meter [0.01]',
                'value_id': 'PowerFactorL3Directional',
                'start_address': 0xC7,
                'value_type': 'S16',
                'scale_factor': -0.01,
            },
            {
                'name': 'Grid Frequency Meter [0.01 Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': 0xC8,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Grid Voltage Total Meter [0.1 V]',
                'value_id': 'VoltageLNAvg',
                'start_address': 0xC9,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage R Meter [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 0xCA,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage S Meter [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 0xCB,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Voltage T Meter [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 0xCC,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current Total Meter [0.1 A]',
                'value_id': 'CurrentLSumImExSum',
                'start_address': 0xCD,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current R Meter [0.1 A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': 0xCE,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current S Meter [0.1 A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': 0xCF,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Grid Current T Meter [0.1 A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': 0xD0,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Solax Hybrid Inverter Battery',
        'virtual_meter': ('Solax Hybrid Inverter', 'Battery'),
        'default_location': 'Battery',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'Battery Voltage [0.1 V]',
                'value_id': 'VoltageDC',
                'start_address': 0x14,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery Current [0.1 A]',
                'value_id': 'CurrentDCChaDisDiff',
                'start_address': 0x15,
                'value_type': 'S16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Battery Power [W]',
                'value_id': 'PowerDCChaDisDiff',
                'start_address': 0x16,
                'value_type': 'S16',
            },
            {
                'name': 'Battery Temperature [°C]',
                'value_id': 'Temperature',
                'start_address': 0x18,
                'value_type': 'S16',
            },
            {
                'name': 'Battery State Of Charge [%]',
                'value_id': 'StateOfCharge',
                'start_address': 0x1C,
                'value_type': 'U16',
            },
            {
                'name': 'Output Energy [0.1 kWh]',
                'value_id': 'EnergyDCDischarge',
                'start_address': 0x1D,
                'value_type': 'U32LE',
                'scale_factor': 0.1,
            },
            {
                'name': 'Input Energy [0.1 kWh]',
                'value_id': 'EnergyDCCharge',
                'start_address': 0x21,
                'value_type': 'U32LE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Solax Hybrid Inverter PV',  # FIXME: some models have PV3, but it's unclear how to detect it properly: https://github.com/evcc-io/evcc/issues/19598
        'virtual_meter': ('Solax Hybrid Inverter', 'PV'),
        'default_location': 'PV',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'PV1 Voltage [0.1 V]',
                'value_id': 'VoltagePV1',
                'start_address': 0x03,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Voltage [0.1 V]',
                'value_id': 'VoltagePV2',
                'start_address': 0x04,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Current [0.1 A]',
                'value_id': 'CurrentPV1Export',
                'start_address': 0x05,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Current [0.1 A]',
                'value_id': 'CurrentPV2Export',
                'start_address': 0x06,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Power [W]',
                'value_id': 'PowerPV1Export',
                'start_address': 0x0A,
                'value_type': 'U16',
            },
            {
                'name': 'PV2 Power [W]',
                'value_id': 'PowerPV2Export',
                'start_address': 0x0B,
                'value_type': 'U16',
            },
            {
                'name': 'Average PV Voltage [0.1 V]',
                'value_id': 'VoltagePVAvg',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Current [0.1 A]',
                'value_id': 'CurrentPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Power [W]',
                'value_id': 'PowerPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Energy [0.1 kWh]',
                'value_id': 'EnergyPVSumExport',
                'start_address': 0x94,  # FIXME: datasheet is unclear if this is the correct register
                'value_type': 'U32LE',
                'scale_factor': 0.1,
            },
        ],
    },
    {
        'name': 'Solax String Inverter',
        'virtual_meter': ('Solax String Inverter', 'Inverter'),
        'default_location': 'Inverter',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'R Phase Output Current [0.1 A]',
                'value_id': 'CurrentL1Export',
                'start_address': 0x40A,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'S Phase Output Current [0.1 A]',
                'value_id': 'CurrentL2Export',
                'start_address': 0x40B,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'T Phase Output Current [0.1 A]',
                'value_id': 'CurrentL3Export',
                'start_address': 0x40C,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'Radiator Temperature [°C]',
                'value_id': 'TemperatureHeatSink',
                'start_address': 0x40D,
                'value_type': 'U16',
            },
            {
                'name': 'Output Power [W]',
                'value_id': 'PowerActiveLSumExport',
                'start_address': 0x40E,
                'value_type': 'U16',
            },
            {
                'name': 'Output Power Signed [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'R Phase Output Power [W]',
                'value_id': 'PowerActiveL1Export',
                'start_address': 0x410,
                'value_type': 'U16',
            },
            {
                'name': 'S Phase Output Power [W]',
                'value_id': 'PowerActiveL2Export',
                'start_address': 0x411,
                'value_type': 'U16',
            },
            {
                'name': 'T Phase Output Power [W]',
                'value_id': 'PowerActiveL3Export',
                'start_address': 0x412,
                'value_type': 'U16',
            },
        ],
    },
    {
        'name': 'Solax String Inverter Grid',
        'virtual_meter': ('Solax String Inverter', 'Grid'),
        'default_location': 'Grid',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'R Phase Grid Voltage [0.1 V]',
                'value_id': 'VoltageL1N',
                'start_address': 0x404,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'S Phase Grid Voltage [0.1 V]',
                'value_id': 'VoltageL2N',
                'start_address': 0x405,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'T Phase Grid Voltage [0.1 V]',
                'value_id': 'VoltageL3N',
                'start_address': 0x406,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'R Phase Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyL1',
                'start_address': 0x407,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'S Phase Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyL2',
                'start_address': 0x408,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'T Phase Grid Frequency [0.01 Hz]',
                'value_id': 'FrequencyL3',
                'start_address': 0x409,
                'value_type': 'U16',
                'scale_factor': 0.01,
            },
            {
                'name': 'Feed In Power [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': 0x43B,
                'value_type': 'S32LE',
                'scale_factor': -1.0,
            },
            {
                'name': 'Feedin Energy Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumExport',
                'start_address': 0x43D,
                'value_type': 'U32LE',
                'scale_factor': 0.01,
            },
            {
                'name': 'Consume Energy Total [0.01 kWh]',
                'value_id': 'EnergyActiveLSumImport',
                'start_address': 0x43F,
                'value_type': 'U32LE',
                'scale_factor': 0.01,
            },
            {
                'name': 'R Phase Feed In Power [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': 0x704,
                'value_type': 'S32LE',
                'scale_factor': -1.0,
            },
            {
                'name': 'S Phase Feed In Power [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': 0x706,
                'value_type': 'S32LE',
                'scale_factor': -1.0,
            },
            {
                'name': 'T Phase Feed In Power [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': 0x708,
                'value_type': 'S32LE',
                'scale_factor': -1.0,
            },
        ],
    },
    {
        'name': 'Solax String Inverter PV',
        'virtual_meter': ('Solax String Inverter', 'PV'),
        'default_location': 'PV',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'PV1 Voltage [0.1 V]',
                'value_id': 'VoltagePV1',
                'start_address': 0x400,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Voltage [0.1 V]',
                'value_id': 'VoltagePV2',
                'start_address': 0x401,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Current [0.1 A]',
                'value_id': 'CurrentPV1Export',
                'start_address': 0x402,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV2 Current [0.1 A]',
                'value_id': 'CurrentPV2Export',
                'start_address': 0x403,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV1 Power [W]',
                'value_id': 'PowerPV1Export',
                'start_address': 0x414,
                'value_type': 'U16',
            },
            {
                'name': 'PV2 Power [W]',
                'value_id': 'PowerPV2Export',
                'start_address': 0x415,
                'value_type': 'U16',
            },
            {
                'name': 'Total PV Energy [0.1 kWh]',
                'value_id': 'EnergyPVSumExport',
                'start_address': 0x423,
                'value_type': 'U32LE',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV3 Voltage [0.1 V]',
                'value_id': 'VoltagePV3',
                'start_address': 0x429,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV3 Current [0.1 A]',
                'value_id': 'CurrentPV3Export',
                'start_address': 0x42A,
                'value_type': 'U16',
                'scale_factor': 0.1,
            },
            {
                'name': 'PV3 Power [W]',
                'value_id': 'PowerPV3Export',
                'start_address': 0x42B,
                'value_type': 'U16',
            },
            {
                'name': 'Average PV Voltage [0.1 V]',
                'value_id': 'VoltagePVAvg',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Current [0.1 A]',
                'value_id': 'CurrentPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
            {
                'name': 'Total PV Power [W]',
                'value_id': 'PowerPVSumExport',
                'start_address': 'START_ADDRESS_VIRTUAL',
            },
        ],
    },
]
