def index_to_address(index):
    return 2100 + 2 * index

specs = [
    {
        'name': 'Tinkerforge WARP Charger',
        'register_type': 'InputRegister',
        'values': [
            {
                'name': 'Phase 1 line to neutral volts [V]',
                'value_id': 'VoltageL1N',
                'start_address': index_to_address(0),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 line to neutral volts [V]',
                'value_id': 'VoltageL2N',
                'start_address': index_to_address(1),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 line to neutral volts [V]',
                'value_id': 'VoltageL3N',
                'start_address': index_to_address(2),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 current [A]',
                'value_id': 'CurrentL1ImExSum',
                'start_address': index_to_address(3),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 current [A]',
                'value_id': 'CurrentL2ImExSum',
                'start_address': index_to_address(4),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 current [A]',
                'value_id': 'CurrentL3ImExSum',
                'start_address': index_to_address(5),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 power [W]',
                'value_id': 'PowerActiveL1ImExDiff',
                'start_address': index_to_address(6),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 power [W]',
                'value_id': 'PowerActiveL2ImExDiff',
                'start_address': index_to_address(7),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 power [W]',
                'value_id': 'PowerActiveL3ImExDiff',
                'start_address': index_to_address(8),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 volt amps [VA]',
                'value_id': 'PowerApparentL1ImExSum',
                'start_address': index_to_address(9),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 volt amps [VA]',
                'value_id': 'PowerApparentL2ImExSum',
                'start_address': index_to_address(10),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 volt amps [VA]',
                'value_id': 'PowerApparentL3ImExSum',
                'start_address': index_to_address(11),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 volt amps reactive [var]',
                'value_id': 'PowerReactiveL1IndCapDiff',
                'start_address': index_to_address(12),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 volt amps reactive [var]',
                'value_id': 'PowerReactiveL2IndCapDiff',
                'start_address': index_to_address(13),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 volt amps reactive [var]',
                'value_id': 'PowerReactiveL3IndCapDiff',
                'start_address': index_to_address(14),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 power factor',
                'value_id': 'PowerFactorL1Directional',
                'start_address': index_to_address(15),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 power factor',
                'value_id': 'PowerFactorL2Directional',
                'start_address': index_to_address(16),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 power factor',
                'value_id': 'PowerFactorL3Directional',
                'start_address': index_to_address(17),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 phase angle [°]',
                'value_id': 'PhaseAngleL1',
                'start_address': index_to_address(18),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 phase angle [°]',
                'value_id': 'PhaseAngleL2',
                'start_address': index_to_address(19),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 phase angle [°]',
                'value_id': 'PhaseAngleL3',
                'start_address': index_to_address(20),
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to neutral volts [V]',
                'value_id': 'VoltageLNAvg',
                'start_address': index_to_address(21),
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line current [A]',
                'value_id': 'CurrentLAvgImExSum',
                'start_address': index_to_address(22),
                'value_type': 'F32BE',
            },
            {
                'name': 'Sum of line currents [A]',
                'value_id': 'CurrentLSumImExSum',
                'start_address': index_to_address(23),
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system power [W]',
                'value_id': 'PowerActiveLSumImExDiff',
                'start_address': index_to_address(24),
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system volt amps [VA]',
                'value_id': 'PowerApparentLSumImExSum',
                'start_address': index_to_address(25),
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system volt amps reactive [var]',
                'value_id': 'PowerReactiveLSumIndCapDiff',
                'start_address': index_to_address(26),
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system power factor',
                'value_id': 'PowerFactorLSumDirectional',
                'start_address': index_to_address(27),
                'value_type': 'F32BE',
            },
            {
                'name': 'Total system phase angle [°]',
                'value_id': 'PhaseAngleLSum',
                'start_address': index_to_address(28),
                'value_type': 'F32BE',
            },
            {
                'name': 'Frequency of supply voltages [Hz]',
                'value_id': 'FrequencyLAvg',
                'start_address': index_to_address(29),
                'value_type': 'F32BE',
            },
            {
                'name': 'Import Wh since last reset [kWh]',
                'value_id': 'EnergyActiveLSumImport', # FIXME: should be mapped resettable
                'start_address': index_to_address(30),
                'value_type': 'F32BE',
            },
            {
                'name': 'Export Wh since last reset [kWh]',
                'value_id': 'EnergyActiveLSumExport', # FIXME: should be mapped resettable
                'start_address': index_to_address(31),
                'value_type': 'F32BE',
            },
            {
                'name': 'Import VArh since last reset [kvarh]',
                'value_id': 'EnergyReactiveLSumInductive', # FIXME: should be mapped resettable
                'start_address': index_to_address(32),
                'value_type': 'F32BE',
            },
            {
                'name': 'Export VArh since last reset [kvarh]',
                'value_id': 'EnergyReactiveLSumCapacitive', # FIXME: should be mapped resettable
                'start_address': index_to_address(33),
                'value_type': 'F32BE',
            },
            {
                'name': 'VAh since last reset [kVAh]',
                'value_id': 'EnergyApparentLSumImExSum', # FIXME: should be mapped resettable
                'start_address': index_to_address(34),
                'value_type': 'F32BE',
            },
            {
                'name': 'Ah since last reset [Ah]',
                'value_id': 'ElectricCharge', # FIXME: should be mapped resettable
                'start_address': index_to_address(35),
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 1 to Line 2 volts [V]',
                'value_id': 'VoltageL1L2',
                'start_address': index_to_address(42),
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 2 to Line 3 volts [V]',
                'value_id': 'VoltageL2L3',
                'start_address': index_to_address(43),
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 3 to Line 1 volts [V]',
                'value_id': 'VoltageL3L1',
                'start_address': index_to_address(44),
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to line volts [V]',
                'value_id': 'VoltageLLAvg',
                'start_address': index_to_address(45),
                'value_type': 'F32BE',
            },
            {
                'name': 'Neutral current [A]',
                'value_id': 'CurrentNImExSum',
                'start_address': index_to_address(46),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 L/N volts THD [%]',
                'value_id': 'VoltageTHDL1N',
                'start_address': index_to_address(47),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 L/N volts THD [%]',
                'value_id': 'VoltageTHDL2N',
                'start_address': index_to_address(48),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 L/N volts THD [%]',
                'value_id': 'VoltageTHDL3N',
                'start_address': index_to_address(49),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 1 Current THD [%]',
                'value_id': 'CurrentTHDL1',
                'start_address': index_to_address(50),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 2 Current THD [%]',
                'value_id': 'CurrentTHDL2',
                'start_address': index_to_address(51),
                'value_type': 'F32BE',
            },
            {
                'name': 'Phase 3 Current THD [%]',
                'value_id': 'CurrentTHDL3',
                'start_address': index_to_address(52),
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to neutral volts THD [%]',
                'value_id': 'VoltageTHDLNAvg',
                'start_address': index_to_address(53),
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line current THD [%]',
                'value_id': 'CurrentTHDLAvg',
                'start_address': index_to_address(54),
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 1 to line 2 volts THD [%]',
                'value_id': 'VoltageTHDL1L2',
                'start_address': index_to_address(61),
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 2 to line 3 volts THD [%]',
                'value_id': 'VoltageTHDL2L3',
                'start_address': index_to_address(62),
                'value_type': 'F32BE',
            },
            {
                'name': 'Line 3 to line 1 volts THD [%]',
                'value_id': 'VoltageTHDL3L1',
                'start_address': index_to_address(63),
                'value_type': 'F32BE',
            },
            {
                'name': 'Average line to line volts THD [%]',
                'value_id': 'VoltageTHDLLAvg',
                'start_address': index_to_address(64),
                'value_type': 'F32BE',
            },
            {
                'name': 'Total kWh [kWh]',
                'value_id': 'EnergyActiveLSumImExSum',
                'start_address': index_to_address(65),
                'value_type': 'F32BE',
            },
            {
                'name': 'Total kvarh [kvarh]',
                'value_id': 'EnergyReactiveLSumIndCapSum',
                'start_address': index_to_address(66),
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 import kWh [kWh]',
                'value_id': 'EnergyActiveL1Import',
                'start_address': index_to_address(67),
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 import kWh [kWh]',
                'value_id': 'EnergyActiveL2Import',
                'start_address': index_to_address(68),
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 import kWh [kWh]',
                'value_id': 'EnergyActiveL3Import',
                'start_address': index_to_address(69),
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 export kWh [kWh]',
                'value_id': 'EnergyActiveL1Export',
                'start_address': index_to_address(70),
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 export kWh [kWh]',
                'value_id': 'EnergyActiveL2Export',
                'start_address': index_to_address(71),
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 export kWh [kWh]',
                'value_id': 'EnergyActiveL3Export',
                'start_address': index_to_address(72),
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 total kWh [kWh]',
                'value_id': 'EnergyActiveL1ImExSum',
                'start_address': index_to_address(73),
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 total kWh [kWh]',
                'value_id': 'EnergyActiveL2ImExSum',
                'start_address': index_to_address(74),
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 total kWh [kWh]',
                'value_id': 'EnergyActiveL3ImExSum',
                'start_address': index_to_address(75),
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 import kvarh [kvarh]',
                'value_id': 'EnergyReactiveL1Inductive',
                'start_address': index_to_address(76),
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 import kvarh [kvarh]',
                'value_id': 'EnergyReactiveL2Inductive',
                'start_address': index_to_address(77),
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 import kvarh [kvarh]',
                'value_id': 'EnergyReactiveL3Inductive',
                'start_address': index_to_address(78),
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 export kvarh [kvarh]',
                'value_id': 'EnergyReactiveL1Capacitive',
                'start_address': index_to_address(79),
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 export kvarh [kvarh]',
                'value_id': 'EnergyReactiveL2Capacitive',
                'start_address': index_to_address(80),
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 export kvarh [kvarh]',
                'value_id': 'EnergyReactiveL3Capacitive',
                'start_address': index_to_address(81),
                'value_type': 'F32BE',
            },
            {
                'name': 'L1 total kvarh [kvarh]',
                'value_id': 'EnergyReactiveL1IndCapSum',
                'start_address': index_to_address(82),
                'value_type': 'F32BE',
            },
            {
                'name': 'L2 total kvarh [kvarh]',
                'value_id': 'EnergyReactiveL2IndCapSum',
                'start_address': index_to_address(83),
                'value_type': 'F32BE',
            },
            {
                'name': 'L3 total kvarh [kvarh]',
                'value_id': 'EnergyReactiveL3IndCapSum',
                'start_address': index_to_address(84),
                'value_type': 'F32BE',
            },
        ],
    },
]
