// Host test for classify_client_hello, extracted from isotls.cpp by
// local_test_client_hello_parser.sh. hellos.inc is generated by
// capture_hellos.py from the local OpenSSL.
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <algorithm>

#include "classify.inc"
#include "hellos.inc"

static int failures = 0;

static const char *name(ClientHelloVersion v)
{
    switch (v) {
        case ClientHelloVersion::Incomplete: return "Incomplete";
        case ClientHelloVersion::Tls13: return "Tls13";
        case ClientHelloVersion::NoTls13: return "NoTls13";
    }
    return "?";
}

static void expect(const char *what, ClientHelloVersion got, ClientHelloVersion want)
{
    if (got != want) {
        printf("FAIL %s: got %s want %s\n", what, name(got), name(want));
        failures++;
    } else {
        printf("ok   %s: %s\n", what, name(got));
    }
}

int main()
{
    const size_t cap = 1024;

    // Full real hellos
    expect("openssl tls13 full", classify_client_hello(hello_tls13, sizeof(hello_tls13), cap), ClientHelloVersion::Tls13);
    expect("openssl tls12 full", classify_client_hello(hello_tls12, sizeof(hello_tls12), cap), ClientHelloVersion::NoTls13);

    // Every prefix must be Incomplete or the correct final answer, never the wrong answer
    for (size_t len = 0; len < sizeof(hello_tls13); len++) {
        ClientHelloVersion v = classify_client_hello(hello_tls13, len, cap);
        if (v == ClientHelloVersion::NoTls13) {
            printf("FAIL tls13 prefix %zu classified NoTls13\n", len);
            failures++;
        }
    }
    printf("ok   tls13 prefixes never NoTls13\n");
    for (size_t len = 0; len < sizeof(hello_tls12); len++) {
        ClientHelloVersion v = classify_client_hello(hello_tls12, len, cap);
        // Tls13 is only acceptable for undeterminable data, which can not
        // happen below cap for a prefix (record incomplete -> Incomplete)
        if (v == ClientHelloVersion::Tls13) {
            printf("FAIL tls12 prefix %zu classified Tls13\n", len);
            failures++;
        }
    }
    printf("ok   tls12 prefixes never Tls13\n");

    // Capped peek: full hello truncated to cap bytes with cap == len must not be Incomplete
    if (sizeof(hello_tls13) > 64) {
        ClientHelloVersion v = classify_client_hello(hello_tls13, 64, 64);
        if (v == ClientHelloVersion::Incomplete) {
            printf("FAIL capped peek returned Incomplete\n");
            failures++;
        } else {
            printf("ok   capped peek: %s\n", name(v));
        }
    }

    // Non-handshake record
    const uint8_t alert[] = {0x15, 0x03, 0x03, 0x00, 0x02, 0x02, 0x28};
    expect("alert record", classify_client_hello(alert, sizeof(alert), cap), ClientHelloVersion::NoTls13);

    // Handshake record, not a ClientHello
    const uint8_t srv_hello[] = {0x16, 0x03, 0x03, 0x00, 0x04, 0x02, 0x00, 0x00, 0x00};
    expect("non ClientHello", classify_client_hello(srv_hello, sizeof(srv_hello), cap), ClientHelloVersion::NoTls13);

    // Minimal ClientHello without extensions (TLS 1.2 style)
    {
        uint8_t hello[128];
        size_t n = 0;
        hello[n++] = 0x16; hello[n++] = 0x03; hello[n++] = 0x01;
        size_t rec_len_at = n; n += 2;
        hello[n++] = 0x01;
        size_t hs_len_at = n; n += 3;
        hello[n++] = 0x03; hello[n++] = 0x03;           // legacy_version
        memset(&hello[n], 0xab, 32); n += 32;           // random
        hello[n++] = 0x00;                              // session_id len
        hello[n++] = 0x00; hello[n++] = 0x02;           // cipher_suites len
        hello[n++] = 0xc0; hello[n++] = 0x23;
        hello[n++] = 0x01; hello[n++] = 0x00;           // compression: 1, null
        size_t hs_len = n - hs_len_at - 3;
        hello[hs_len_at] = 0; hello[hs_len_at + 1] = (uint8_t)(hs_len >> 8); hello[hs_len_at + 2] = (uint8_t)hs_len;
        size_t rec_len = n - rec_len_at - 2;
        hello[rec_len_at] = (uint8_t)(rec_len >> 8); hello[rec_len_at + 1] = (uint8_t)rec_len;
        expect("no extensions", classify_client_hello(hello, n, cap), ClientHelloVersion::NoTls13);
        for (size_t len = 0; len < n; len++) {
            if (classify_client_hello(hello, len, cap) == ClientHelloVersion::Tls13) {
                printf("FAIL no-ext prefix %zu classified Tls13\n", len);
                failures++;
            }
        }
        printf("ok   no-ext prefixes never Tls13\n");
    }

    // supported_versions with only 0x0303 (TLS 1.2 via the 1.3 extension)
    {
        uint8_t hello[128];
        size_t n = 0;
        hello[n++] = 0x16; hello[n++] = 0x03; hello[n++] = 0x01;
        size_t rec_len_at = n; n += 2;
        hello[n++] = 0x01;
        size_t hs_len_at = n; n += 3;
        hello[n++] = 0x03; hello[n++] = 0x03;
        memset(&hello[n], 0xab, 32); n += 32;
        hello[n++] = 0x00;
        hello[n++] = 0x00; hello[n++] = 0x02;
        hello[n++] = 0xc0; hello[n++] = 0x23;
        hello[n++] = 0x01; hello[n++] = 0x00;
        hello[n++] = 0x00; hello[n++] = 0x07;           // extensions len
        hello[n++] = 0x00; hello[n++] = 0x2b;           // supported_versions
        hello[n++] = 0x00; hello[n++] = 0x03;
        hello[n++] = 0x02; hello[n++] = 0x03; hello[n++] = 0x03;
        size_t hs_len = n - hs_len_at - 3;
        hello[hs_len_at] = 0; hello[hs_len_at + 1] = (uint8_t)(hs_len >> 8); hello[hs_len_at + 2] = (uint8_t)hs_len;
        size_t rec_len = n - rec_len_at - 2;
        hello[rec_len_at] = (uint8_t)(rec_len >> 8); hello[rec_len_at + 1] = (uint8_t)rec_len;
        expect("supported_versions 0x0303 only", classify_client_hello(hello, n, cap), ClientHelloVersion::NoTls13);
    }

    // Empty and tiny inputs
    expect("empty", classify_client_hello(hello_tls13, 0, cap), ClientHelloVersion::Incomplete);
    expect("4 bytes", classify_client_hello(hello_tls13, 4, cap), ClientHelloVersion::Incomplete);

    printf("%s (%d failures)\n", failures == 0 ? "PASS" : "FAIL", failures);
    return failures == 0 ? 0 : 1;
}
