#!/bin/bash
DIRNAME2=$(basename "$(dirname " $(realpath .)")")/$(basename " $(realpath .)")
docker run \
       --rm \
       -v $(realpath ../..):/tf \
       tinkerforge/build_environment_esp32 \
       /bin/bash -c "groupmod -g $(id -g) $(id -gn) || groupadd -g $(id -g) $(id -gn) && usermod -u $(id -u) -g $(id -g) pio && su pio -c \"cd /tf/$DIRNAME2 && pio $*\""
