#!/usr/bin/env python3

import argparse
import os
import sys
import signal
import subprocess
import serial

parser = argparse.ArgumentParser()
parser.add_argument("firmware", nargs='?', default=None)
parser.add_argument("-a", "--all", action="store_true")
args = parser.parse_args()

def get_latest_fw(fw_type=''):
    files = os.listdir("build")
    files = [x for x in files if x.endswith(".elf") and (fw_type == '' or x.startswith(fw_type + "_firmware"))]
    latest = max(files, key=lambda x: int(x.replace(".elf", "").replace("-WITH-WIFI-PASSPHRASE-DO-NOT-DISTRIBUTE", "").split("_firmware_")[1].split("_")[3], 16), default=None)
    if latest is None:
        print("Failed to find a firmware containing the string {}".format(fw_type))
        sys.exit(0)
    return os.path.join("build", latest)

if args.firmware is None:
    firmware = get_latest_fw()
else:
    if ".elf" in args.firmware:
        firmware = args.firmware
    if "_merged.bin" in args.firmware:
        firmware = args.firmware.replace("_merged.bin", ".elf")
    else:
        firmware = get_latest_fw(args.firmware)

os.system("nm -l --demangle --print-size --size-sort --radix=d --format sysv -s {}{}".format(firmware, "" if args.all else "| grep -v '|.flash'"))
print(firmware)
