[env:warp4]
extends = env:warp3

board_build.partitions = default_16MB_secure.csv
custom_split_esptool_ota = true

platform_packages = platformio/framework-arduinoespressif32 @ https://github.com/Tinkerforge/arduino-esp32#a1a8a3046dc3f360924d7f494bd5a5b14df2d9c5
                    platformio/framework-arduinoespressif32-libs @ symlink://packages/esp32-arduino-libs#tf-esp-secure-20260612_48650e8e869d4f7aed0297082d37d851d66cee78

lib_deps = ${env:warp3.lib_deps}
           https://github.com/Tinkerforge/libcbv2g

build_flags = ${env:warp3.build_flags}
              -DTF_HAL_ESPIDF=1

custom_product_id = warp4

custom_options = ${env:warp3.custom_options}
                 product_name = "WARP4 Charger"
                 hostname_prefix = "warp4"
                 meters_slot_1_default_class = MeterClassID::ISO15118
                 firmware_update_latest_url = "https://www.warp-charger.com/downloads/#firmwares-warp4"
                 firmware_update_index_version = 3
                 manual_url = "https://www.warp-charger.com/downloads/#documents-warp4"
                 min_data_partition_format = 2 ; LittleFS in partition "data"
                 ;esp32_common_enable_secure_boot_api = 1 ; Provisioning only
                 ;esp32_common_dump_default_wifi_passphrase = 1 ; Provisioning only
                 ;factory_data_enable_write_api = 1 ; Provisioning only

; Intentionally inherit WARP2: WARP3 adds Warp Esp32 I2c/Rtc. We don't want those.
custom_backend_modules = ${env:warp2.custom_backend_modules}
                         ISO15118
                         Meters ISO15118
                         Ev
                         ESP32 Ethernet V2 Co Bricklet
                         Factory Data
                         Debug

; Intentionally inherit WARP2: WARP3 and WARP2 frontend module lists are the same,
; but "WARP4 inherits all WARP2 modules" is simpler than mixing where we inherit from.
custom_frontend_modules = ${env:warp2.custom_frontend_modules}
                          ISO15118
                          Meters ISO15118
                          Ev
                          Factory Data
                          Debug

custom_frontend_components = EVSE Group $ Open
                               Evse Common | EVSE Settings
                               Evse Common | EVSE
                               ISO15118
                               Charge Tracker
                               Automation
                             EVSE Group $ Close
                             Energy Management Group $ Open
                               Meters
                               Batteries
                               Charge Manager | Charge Manager Chargers
                               Power Manager | PV Excess Settings
                               Charge Manager | Charge Manager Settings
                               Day Ahead Prices
                               Solar Forecast
                               Eco
                               P14a Enwg
                             Energy Management Group $ Close
                             Network Group $ Open
                               Network
                               Wifi | Wifi STA
                               Wifi | Wifi AP
                               Ethernet
                               Wireguard
                             Network Group $ Close
                             Interfaces Group $ Open
                               Mqtt
                               Modbus TCP
                               Ocpp
                               EEBus
                             Interfaces Group $ Close
                             Users Group $ Open
                               Users
                               Ev
                             Users Group $ Close
                             System Group $ Open
                               System
                               Certs
                               Remote Access
                               Time
                               Event Log
                               Firmware Update
                             System Group $ Close
                             Debug

custom_frontend_status_components = Device Name
                                    Status Alerts
                                    Evse Common | EVSE Status
                                    Power Manager
                                    Charge Limits
                                    Meters
                                    Charge Tracker
                                    Wifi
                                    Ethernet
                                    Wireguard
                                    Mqtt
                                    Ocpp
                                    Remote Access
                                    Time
                                    Charge Manager | Charge Manager Heading
                                    Charge Manager | Charge Manager Mode Buttons
                                    Eco
                                    Charge Manager

; ============================================================================

[env:warp4_screenshot]
extends = env:warp4

;custom_options = ${env:warp4.custom_options}
;                 screenshot_data_faker_pro = 1

custom_backend_modules = ${env:warp4.custom_backend_modules}
                         Screenshot Data Faker

; ============================================================================

[env:warp4_debug]
extends = env:warp4

custom_frontend_debug = true

; ============================================================================

[env:warp4_web]
extends = env:warp4

custom_web_only = true

; ============================================================================

[env:warp4_web_debug]
extends = env:warp4

custom_web_only = true
custom_frontend_debug = true

; ============================================================================

[env:warp4_signed]
extends = env:warp4

custom_signature_preset = warp:v1

; ============================================================================

[env:warp4_nightly]
extends = env:warp4

build_flags = ${env:warp4.build_flags}
              -DNIGHTLY

; ============================================================================

[env:warp4_nightly_signed]
extends = env:warp4

build_flags = ${env:warp4.build_flags}
              -DNIGHTLY

custom_signature_preset = warp:v1
