[Dependencies]
Requires = Task Scheduler
           Event Log
           API
           Meters

[Options]
; the default display name has to be configured in the env
meters_rs485_bricklet_default_display_name =
