

# This Script generates the C++ code for the SPINE Types required for EEBUS
# It is only tested for SPINE 1.3.0 and might not work properly
# Place ALL SPINE XSD files in the <spine_path> directory. By default this is "./SPINE"
# The generated code is written to "spine_types.h" and "spine_types.cpp"


spine_path = "SPINE"
output_header = "spine_types.h"
output_cpp = "spine_types.cpp"

# yes i am aware this code is not very good looking but it works and handles all the edgecases i could find

import xmlschema
import os



cpp_header_header = """
// This file is generated by generator.py. Changes will be overwritten

#pragma once

#include "module.h"
#include "config.h"
#include <string>
#include <vector>
#include <map>
#include <optional>

namespace ArduinoJson {
template <typename T>
struct Converter<std::vector<T> > {
  static void toJson(const std::vector<T>& src, JsonVariant dst) {
    JsonArray array = dst.to<JsonArray>();
    for (T item : src)
      array.add(item);
  }

  static std::vector<T> fromJson(JsonVariantConst src) {
    std::vector<T> dst;
    for (T item : src.as<JsonArrayConst>())
      dst.push_back(item);
    return dst;
  }

  static bool checkJson(JsonVariantConst src) {
    JsonArrayConst array = src;
    bool result = array;
    for (JsonVariantConst item : array)
      result &= item.is<T>();
    return result;
  }
};
}  // namespace ArduinoJson

struct DateTimeStruct { // Added manually
    std::optional<uint16_t> year;
    std::optional<uint8_t> month;
    std::optional<uint8_t> day;
    std::optional<uint8_t> hour;
    std::optional<uint8_t> minute;
    std::optional<uint8_t> second;
    std::optional<uint16_t> millisecond;
    std::optional<int8_t> timezone; // Offset from UTC in hours, 0 if time is UTC, empty if no TZ is given
};


"""

cpp_implementation_header = """
// This file is generated by generator.py. Changes will be overwritten
#include "spine_types.h"


"""

unprocessed_elements = 0



class Spine_type:
    #@brief: Type_name: either "define", "using", "enum", "struct" or "class"
    type_name = ""
    depends_on = []
    name = ""
    code = ""
    to_json_code = ""
    from_json_code = ""
    upper_limit = None
    lower_limit = None
    #this is technically required but we dont check it
    regex_restriction = None

    def __init__(self, type_name, name, code):
        self.type_name = type_name
        self.name = name
        self.code = code
        self.depends_on = []

cpp_datatypes : list[Spine_type] = []

# This maps SPINE Functions to the datatypes
type_function_mapping: list[tuple[str, str]] = []


def remove_namespace(name):
    if name is not None:
        if "}" in name:
            return name.split("}", 1)[1]  # Entfernt den Namespace-URI
    else:
        return "None"
    return name

def to_cpp_datatype(type_name):
    #type_name = str(type_name.__name__)
    if hasattr(type_name, "__name__"):
        type_name_str = str(type_name.__name__)
    else:
        type_name_str = type_name
    type_mapping = {
        "string": "std::string",
        "str": "std::string",
        "int": "int",
        "integer": "int",
        "float": "float",
        "double": "double",
        "boolean": "bool",
        "bool": "bool",
        "duration": "std::string", # For now we push all these into strings and handle them later
        "datetime10": "std::string",
        "datetime": "std::string",
        "date": "std::string",
        "time": "std::string",
        "unsignedint": "uint32_t",
        "unsignedbyte": "uint8_t",
        "unsignedlong": "uint64_t",
        "hexbinary": "std::string", # this might be better to convert to byte array
    }
    #if type_name not in type_mapping:
    #       print("Unknown datatype:", type_name)
    return type_mapping.get(type_name_str.lower(), type_name)

def remove_duplicate_objects(spine_types: list[Spine_type]):
    seen = set()
    result = []
    for spine_type in spine_types:
        if spine_type.name not in seen:
            seen.add(spine_type.name)
            result.append(spine_type)
    return result

def remove_duplicate_function_mappings(type_function_mapping: list[tuple[str, str]]):
    seen = set()
    result = []
    for mapping in type_function_mapping:
        if mapping not in seen:
            seen.add(mapping)
            result.append(mapping)
    return result

def sort_and_resolve_dependencies(spine_types: list[Spine_type]):
    type_order = {"define": 0, "using": 1, "enum": 2, "struct": 3, "class": 4}

    dependency_map = {datatype_l.name: datatype_l.depends_on for datatype_l in cpp_datatypes}

    sorted_datatypes = []
    visited = set()

    def visit(datatype_v):
        if datatype_v.name in visited:
            return
        visited.add(datatype_v.name)
        for dependency in dependency_map.get(datatype_v.name, []):
            dependent_datatype = next((d for d in cpp_datatypes if d.name == dependency), None)
            if dependent_datatype:
                visit(dependent_datatype)
        sorted_datatypes.append(datatype_v)

    cpp_datatypes.sort(key=lambda x: type_order.get(x.type_name, 5))
    for datatype_l in cpp_datatypes:
        visit(datatype_l)

    return sorted_datatypes

def make_variable_name(name: str):
    forbidden_names = ["switch", "auto", "SAR", "delete"]
    #Cleanup the variable so it can be used in C++
    name = ''.join(char if char.isalnum() else '_' for char in name)
    # Stelle sicher, dass der Name mit einem Buchstaben beginnt
    if not name[0].isalpha() or name[0] in forbidden_names or name in forbidden_names:
        name = 'var_' + name
    return name

def process_complex_type(complex_type):
    global unprocessed_elements
    struct_type_name = remove_namespace(complex_type.name)
    #we dont generate cmdtype and datagramtype. They are handled differently
    if struct_type_name == "CmdType" or struct_type_name == "DatagramType" or struct_type_name == "PayloadType":
        return
    new_type = Spine_type("struct", struct_type_name, "")
    if hasattr(complex_type.content, "content_type_label") and complex_type.content.content_type_label == "simple":
        new_type = Spine_type("using", remove_namespace(complex_type.name), "")
        new_type.code = "using " + remove_namespace(complex_type.name) + " = " + to_cpp_datatype(complex_type.base_type.python_type) + "; \n"
        cpp_datatypes.append(new_type)
        return
    elif complex_type.content.model == "sequence":
        sequence_size = len(complex_type.content)
        elements = []
        new_type.code = f"struct {struct_type_name} {{ // {complex_type.schema.name}\n"
        new_type.to_json_code = f"""bool convertToJson(const {struct_type_name} &src, JsonVariant& dst) {{\n"""

        new_type.from_json_code = f"""void convertFromJson(const JsonVariantConst& src, {struct_type_name} &dst) {{\n"""
        for elem in complex_type.content:
            variable_type = variable_name = ""
            is_vec = False
            if hasattr(elem, "model"):
                if elem.model == "sequence":
                    if len(elem) > 0:
                        for sub_elem in elem:
                            if len(sub_elem) == 1:
                                sub_elem = sub_elem[0]
                            elif len(sub_elem) > 1:
                                print("Sub element too long")
                            is_vec = sub_elem.max_occurs != 1
                            variable_name = make_variable_name(remove_namespace(sub_elem.name))
                            if not hasattr(sub_elem, "type") and hasattr(sub_elem, "local_name"):
                                variable_type = remove_namespace(sub_elem.local_name)
                            else:
                                variable_type = remove_namespace(sub_elem.type.name)
                            element = [variable_type, variable_name, is_vec]
                            elements.append(element)
                    else:
                        print("unprocessed element: " + struct_type_name + " has model type sequence but no type can be determined")
                        unprocessed_elements += 1
                        return
                else:
                    if struct_type_name == "FilterType":
                        #We dont care about the filtertype. Its done manually
                        return
                    print("unprocessed element: " + struct_type_name + " has model type but is not sequence")
                    unprocessed_elements +=1
                    return
            else:
                variable_name = remove_namespace(elem.name)
                variable_type = remove_namespace(elem.type.name)

                if variable_type is None or variable_type == "None":
                    variable_type = remove_namespace( elem.type.base_type.name)
                if variable_type is None or variable_type == "None":
                    print("Variable type is still none")
                    unprocessed_elements += 1
                    return
                if elem.max_occurs is None:
                    is_vec = True
                element = [variable_type, variable_name, is_vec]
                elements.append(element)
        for variable_type, variable_name, is_vec  in elements:
            if variable_type == to_cpp_datatype(variable_type):
                new_type.depends_on.append(variable_type)
            variable_type = to_cpp_datatype(variable_type)
            variable_name_string = variable_name
            variable_name_cpp = make_variable_name(variable_name)

            # Handle edgecases
            if variable_type == "SpecificationVersionDataType": # This is some weird edgecase
                variable_type = "SpecificationVersionType"

            # Done
            if is_vec:
                variable_type = "std::vector<" + variable_type + ">"
            new_type.code += f"\tstd::optional<{variable_type}> {variable_name_cpp};\n"
            if variable_type == "None" or variable_type is None:
                print("Variable type is None while making complex type")
                unprocessed_elements += 1
                return
            new_type.to_json_code += f"""\tif (src.{variable_name_cpp}) {{\n\t\tdst["{variable_name_string}"] = *src.{variable_name_cpp};\n\t}}\n"""
            new_type.from_json_code += f"""\tif (src["{variable_name_string}"]) {{\n\t\tdst.{variable_name_cpp} = src["{variable_name_string}"].as<decltype(dst.{variable_name_cpp})::value_type>();\n\t}} else {{\n\t\tdst.{variable_name_cpp} = std::nullopt;\n\t}}\n"""
        if len(elements) < 1:
            new_type.to_json_code = f"""bool convertToJson(const {struct_type_name} &src, JsonVariant& dst) {{\n"""
            new_type.from_json_code = f"""void convertFromJson(const JsonVariantConst& src, {struct_type_name} &dst) {{\n"""

        new_type.code += "};\n"
        new_type.code += f"""bool convertToJson(const {struct_type_name} &src, JsonVariant& dst);\n"""
        new_type.code += f"""void convertFromJson(const JsonVariantConst& src, {struct_type_name} &dst);\n\n"""

        new_type.to_json_code += "\n\treturn true;\n}\n"
        new_type.from_json_code += "\n}\n"
        cpp_datatypes.append(new_type)
        #print("type is sequence")
    #print("Generating code for complex type", remove_namespace(complex_type.name))
    # print("Generating code for complex type", remove_namespace(complex_type.name))




def process_schema(xml_schema):
    global unprocessed_elements
    #print("Generating code...")
    for simple_type in xml_schema.simple_types:

        if simple_type.derivation == "restriction":
            #restriction implies it is either a simple like "using Number = int" or an enum
            # Enum
            if simple_type.enumeration is not None:
                enum_type_name = remove_namespace(simple_type.name)
                new_type = Spine_type("enum",enum_type_name, "")
                #create enum and function headers
                new_type.code = "enum class " + enum_type_name + " { // " + simple_type.schema.name +"\n"
                new_type.to_json_code = f"""bool convertToJson(const {enum_type_name} &src, JsonVariant& dst) {{\n\tString enumName;\n\tswitch(src) {{\n"""
                new_type.from_json_code = f"""void convertFromJson(const JsonVariantConst& src, {enum_type_name} &dst) {{\n"""

                enum_variable_name = ""
                for enumeration in simple_type.enumeration:
                    enum_string_name = str(enumeration)
                    enum_variable_name = make_variable_name(enum_string_name)
                    new_type.code += "\t" + enum_variable_name + ",\n"
                    #switch case for enum->json
                    new_type.to_json_code += f"""\tcase {enum_type_name}::{enum_variable_name}:\n\t\t enumName = "{enum_string_name}";\n\t\tbreak;\n"""
                    #if return for json->enum
                    new_type.from_json_code += f"""\tif (src == "{enum_string_name}") {{\n\t\tdst = {enum_type_name}::{enum_variable_name};\n\t\treturn;\n\t}}\n"""

                #return empty string if enum->json fails (shouldn't happen)
                new_type.to_json_code += "\t} \n\tdst.set(enumName);\n\treturn true;\n}\n"
                #return last enum if json->enum fails
                new_type.from_json_code += f"""\t return;\n}}\n"""
                new_type.code += "};\n"
                new_type.code += f"""bool convertToJson(const {enum_type_name} &src, JsonVariant& dst);\n"""
                new_type.code += f"""void convertFromJson(const JsonVariantConst& src, {enum_type_name} &dst);\n\n"""
                cpp_datatypes.append(new_type)
            # Using
            elif hasattr(simple_type, 'base_type'):
                new_type = Spine_type("using", remove_namespace(simple_type.name), "")

                new_type.code = "using " + remove_namespace(simple_type.name) + " = " + to_cpp_datatype(simple_type.base_type.python_type) + ";\n"
                found_restriction = False
                if simple_type.base_type.max_value is not None:
                    new_type.max_value = simple_type.base_type.max_value
                    pass
                if simple_type.base_type.min_value is not None:
                    found_restriction = True
                    new_type.min_value = simple_type.base_type.min_value
                    found_restriction = True
                if to_cpp_datatype(simple_type.base_type.python_type) == "std::string":
                    found_restriction = True
                if hasattr(simple_type.base_type.python_type, 'name'):
                    if simple_type.base_type.python_type.name == "duration":
                        found_restriction = True
                if not found_restriction:
                    print("Unknown restriction to basetype", simple_type.name)
                cpp_datatypes.append(new_type)
                pass
            else:
                unprocessed_elements += 1
                print("simple type: " + simple_type.name + " has restriction but no enumeration. Not sure what to do with this")
        else:
            # else its a union
            if hasattr(simple_type, 'member_types'):
                new_type = Spine_type("using", remove_namespace(simple_type.name), "")
                new_type.code = "using " + remove_namespace(simple_type.name) + " = " + to_cpp_datatype(simple_type.python_type) + ";\n"
                cpp_datatypes.append(new_type)

            else:
                print("Unidentified Type", simple_type.name)
                unprocessed_elements += 1
    for complex_type in xml_schema.complex_types:
        process_complex_type(complex_type)

    ignored_types = ["filtertype", "payloadtype", "datagramtype", "hexbinary"]
    ignored_names = ["device", "entity", "feature", "hexbinary"]
    for element_name in xml_schema.elements.target_dict:
        if "{http://www.w3.org/2001/XMLSchema}" not in element_name:
            element_name_short = remove_namespace(element_name)
            element_type = remove_namespace(xml_schema.elements.target_dict[element_name].type.name)
            if element_name_short.lower() not in ignored_names and element_type.lower() not in ignored_types:
                mapping = (element_name_short, element_type)
                type_function_mapping.append(mapping)
        #print("Generating code for element", remove_namespace(element))


# Yes this i am aware this is really ugly python code
def generate_data_handler_class() -> (str,str):
    function_enum_entries = ''.join(f"\n\t\t\t{function[0]}," for function in type_function_mapping)
    type_enum_entries = ''.join(f"\n\t\t\t{function[1]}," for function in type_function_mapping)
    function_to_type_mapping = ''.join(f"\n\t\tcase SpineDataTypeHandler::Function::{function[0]}: return SpineDataTypeHandler::Type::{function[1]};" for function in type_function_mapping)
    string_to_function_mapping = ''.join(f"\n\tif (function_name == \"{function[0]}\") return SpineDataTypeHandler::Function::{function[0]};" for function in type_function_mapping)
    function_to_string_mapping = ''.join(f"\n\tif (function == SpineDataTypeHandler::Function::{function[0]}) return \"{function[0]}\";" for function in type_function_mapping)



    data_types = ''.join(f"\n\t\tstd::optional<{cpp_datatype.name}> {cpp_datatype.name.lower()};" for cpp_datatype in cpp_datatypes)

    cmd_types = ''.join(f"""
    if (obj["{function[0]}"]) {{
        last_cmd = function_from_string("{function[0]}");
        {function[1].lower()} =  obj["{function[0]}"].as<decltype({function[1].lower()})::value_type>();  
        return last_cmd;
    }}""" for function in type_function_mapping)

    output_h = f"""
class SpineDataTypeHandler {{
    public:

        {data_types}
        enum class Function {{{function_enum_entries}
        None
        }};  
        enum class Type {{{type_enum_entries}
        None
        }};
        
        
        Function last_cmd;
        
        Type type_from_function(Function function);
        Function function_from_string(const String function_name);
        Function handle_cmd(JsonObjectConst obj);
        String function_to_string(Function function);
}};
    """
    output_cpp_code = f"""
SpineDataTypeHandler::Type SpineDataTypeHandler::type_from_function(SpineDataTypeHandler::Function function) {{
    switch(function) {{{function_to_type_mapping}
    default:    
        return SpineDataTypeHandler::Type::None;
    }}
    return SpineDataTypeHandler::Type::None;
}}

SpineDataTypeHandler::Function SpineDataTypeHandler::function_from_string(const String function_name) {{
{string_to_function_mapping}
    return SpineDataTypeHandler::Function::None;
}}

SpineDataTypeHandler::Function SpineDataTypeHandler::handle_cmd(JsonObjectConst obj) {{
    {cmd_types}
    return SpineDataTypeHandler::Function::None;
}}
String SpineDataTypeHandler::function_to_string(Function function) {{
    {function_to_string_mapping}
    return "Unknown function";
}}
    """

    return output_h, output_cpp_code

print("Loading schema...")



for xsd in os.listdir(spine_path):
    if xsd.endswith(".xsd"):
        print("Processing: " + xsd)
        schema = xmlschema.XMLSchema(os.path.join(spine_path, xsd))
        if schema.version != "1.3.0":
            print("WARNING: Schema version is not 1.3.0. This might cause issues.")
        process_schema(schema)


print("Deduplicating and sorting code...")
print("Elements Before: ", len(cpp_datatypes))
print("Functions before: ", len(type_function_mapping))
cpp_datatypes = remove_duplicate_objects(cpp_datatypes)
type_function_mapping = remove_duplicate_function_mappings(type_function_mapping)
print("Elements After: ", len(cpp_datatypes))
print("Functions after: ", len(type_function_mapping))
print("Resolving Type Dependencies...")
cpp_datatypes = sort_and_resolve_dependencies(cpp_datatypes)


data_handler_header, data_handler_cpp = generate_data_handler_class()

print("Writing code to files...")
with open(output_header, "w")as h, open(output_cpp, "w") as cpp:
    h.write(cpp_header_header)
    cpp.write(cpp_implementation_header)
    h.write("\n\n\n\n")
    for datatype in cpp_datatypes:
        h.write(datatype.code)
        cpp.write(datatype.to_json_code)
        cpp.write(datatype.from_json_code)
    h.write("\n\n\n\n")
    h.write(data_handler_header)
    cpp.write(data_handler_cpp)


with open(output_header, "r") as h, open(output_cpp, "r") as cpp:
    print(f"Wrote {len(h.readlines())} LOC to header ")
    print(f"Wrote {len(cpp.readlines())} LOC to cpp")

print(f"Unprocessed elements: {unprocessed_elements}")

print("Done!")

# TODO: Add more documentation on how to use this