[Dependencies]
Requires = Task Scheduler
           Event Log
           EM Common
           Meters

[Options]
; the default display name has to be configured in the env
meters_em_default_display_name =
