[Dependencies]
Requires = Task Scheduler
           Event Log
           Web Server
           API

Optional = Debug
           Meters
           Config Import

; The order 'Task Scheduler', 'Event Log', 'API' must be exactly this one:
; API::setup migrates the config and expects that tasks can be scheduled and the logger is initialized
After = Task Scheduler
        Event Log
