#ifdef __GNUC__
#pragma GCC diagnostic error "-Wall"
#pragma GCC diagnostic error "-Wextra"

#pragma GCC diagnostic error "-Walloc-zero"
#pragma GCC diagnostic error "-Walloca-larger-than=1"
#pragma GCC diagnostic error "-Wcast-align"
#pragma GCC diagnostic error "-Wcast-qual"
#pragma GCC diagnostic error "-Wconditionally-supported"
#pragma GCC diagnostic error "-Wctor-dtor-privacy"
#pragma GCC diagnostic error "-Wdisabled-optimization"
#pragma GCC diagnostic error "-Wdouble-promotion"
#pragma GCC diagnostic error "-Wduplicated-branches"
#pragma GCC diagnostic error "-Wduplicated-cond"
#pragma GCC diagnostic error "-Weffc++"
#pragma GCC diagnostic error "-Wextra-semi"
#pragma GCC diagnostic error "-Wfloat-equal"
#pragma GCC diagnostic error "-Wformat=2"
#pragma GCC diagnostic error "-Wformat-nonliteral"
#pragma GCC diagnostic error "-Wformat-security"
#pragma GCC diagnostic error "-Wformat-signedness"
#pragma GCC diagnostic error "-Wformat-y2k"
#pragma GCC diagnostic error "-Winit-self"
#pragma GCC diagnostic error "-Winvalid-pch"
#pragma GCC diagnostic error "-Wlogical-op"
#pragma GCC diagnostic error "-Wmissing-declarations"
#pragma GCC diagnostic error "-Wmissing-format-attribute"
#pragma GCC diagnostic error "-Wmissing-include-dirs"
#pragma GCC diagnostic error "-Wmissing-noreturn"
#pragma GCC diagnostic error "-Wnamespaces"
#pragma GCC diagnostic error "-Wnoexcept"
#pragma GCC diagnostic error "-Wnull-dereference"
#pragma GCC diagnostic error "-Woverloaded-virtual"
#pragma GCC diagnostic error "-Wpacked"
#pragma GCC diagnostic error "-Wpedantic"
#pragma GCC diagnostic error "-Wpointer-arith"
#pragma GCC diagnostic error "-Wredundant-decls"
#pragma GCC diagnostic error "-Wregister"
#pragma GCC diagnostic error "-Wstack-protector"
#pragma GCC diagnostic error "-Wstrict-null-sentinel"
#pragma GCC diagnostic error "-Wstrict-overflow=2"
#pragma GCC diagnostic error "-Wsuggest-attribute=const"
#pragma GCC diagnostic error "-Wsuggest-attribute=format"
#pragma GCC diagnostic error "-Wsuggest-attribute=malloc"
#pragma GCC diagnostic error "-Wsuggest-final-types"
#pragma GCC diagnostic error "-Wsuggest-final-methods"
#pragma GCC diagnostic error "-Wsuggest-override"
#pragma GCC diagnostic error "-Wswitch-default"
#pragma GCC diagnostic error "-Wswitch-enum"
#pragma GCC diagnostic error "-Wtrampolines"
#pragma GCC diagnostic error "-Wundef"
#pragma GCC diagnostic error "-Wunreachable-code"
#pragma GCC diagnostic error "-Wunsafe-loop-optimizations"
#pragma GCC diagnostic error "-Wunused"
#pragma GCC diagnostic error "-Wuseless-cast"
#pragma GCC diagnostic error "-Wvariadic-macros"
#pragma GCC diagnostic error "-Wvla"
#pragma GCC diagnostic error "-Wwrite-strings"
#pragma GCC diagnostic error "-Wzero-as-null-pointer-constant"

#pragma GCC diagnostic error "-Wframe-larger-than=4096"
#pragma GCC diagnostic error "-Wstack-usage=4096"

// signed/unsigned
#pragma GCC diagnostic error "-Wconversion"
#pragma GCC diagnostic error "-Wsign-compare"
#pragma GCC diagnostic error "-Wsign-conversion"
#pragma GCC diagnostic error "-Wsign-promo"

// expect pain
#pragma GCC diagnostic error "-Wformat-overflow=2"
#pragma GCC diagnostic error "-Wold-style-cast"
#pragma GCC diagnostic error "-Wshadow"
#endif
