// WARNING: This file is generated by "src/modules/iso15118/tools/certs/generate_certs.sh"

// Embedded test certificates for development/testing
// Certificate chain: SECC Leaf -> CPO Sub-CA2 -> CPO Sub-CA1

#include "dev_certs.h"

#include "gcc_warnings.h"

// =============================================================================
// ISO 15118-2 Certificates (secp256r1/prime256v1, TLS 1.2)
// =============================================================================
// [V2G2-006] ECC-based using secp256r1 curve
// [V2G2-007] Key length for ECC shall be 256 bit

const char dev_cert_chain_pem_iso2[] =
    // SECC Leaf Certificate
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB2DCCAX+gAwIBAgICMDwwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0EyMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjAyMDcyMDMyMjhaFw0yNjA0MDgyMDMyMjhaMEQxETAPBgNVBAMM\n"
    "CFNFQ0NDZXJ0MQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT\n"
    "8ixkARkWA0NQTzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPb0nBsGrxXPfQbe\n"
    "7tGN8fs9mMRJblzy2HOjewV2l5Oebrx0iQ9BciYuCsa8/lLOZyiS+pHQ/CvaKpO6\n"
    "Qn7YYjSjYDBeMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgOIMB0GA1UdDgQW\n"
    "BBRoPAAMuMS+qElVRvsAQqrcPDyjpDAfBgNVHSMEGDAWgBSSWBz8CSXISStPJGsC\n"
    "DE0h9ezTozAKBggqhkjOPQQDAgNHADBEAiBQ0qjYgixu36NFys9iiMXjKwUGrtCY\n"
    "oeTMErDwlhNGsAIgAz9loqKqByJJXJg17Hxu1jPbsGLyYxyrTZ57Fg1wus8=\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 2
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB4DCCAYagAwIBAgICMDswCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0ExMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjAyMDcyMDMyMjhaFw0yNzAyMDcyMDMyMjhaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMjENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASATob9uS6xpUeT\n"
    "DuQETZtZdsFPQOBLsTgRusTZrM7P4jsahnhpsllSNWt5S+9bLNiFgn9cDlpHrWsa\n"
    "k2rpXKcJo2YwZDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAd\n"
    "BgNVHQ4EFgQUklgc/AklyEkrTyRrAgxNIfXs06MwHwYDVR0jBBgwFoAU/jOS2yH3\n"
    "LuOyXByTQy6sF1U4gJcwCgYIKoZIzj0EAwIDSAAwRQIhAJYxcK5yrIrsiVpqK98m\n"
    "HtNJUfE8b0FZpceA9haqCiSVAiAT0QOXIs2cVL4vW+5pyRfL82pb6QnecDqbJn32\n"
    "t4CG5w==\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 1
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB3jCCAYagAwIBAgICMDowCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjAyMDcyMDMyMjhaFw0zMDAyMDYyMDMyMjhaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASDHpvFKKZdhdSA\n"
    "o/tltTlI+BQjV/KqNXRmxR7w4e63u16rroRJ8UntI5uf2ZewF6Qx+wCysAJR60rJ\n"
    "ljd9rhw1o2YwZDASBgNVHRMBAf8ECDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBBjAd\n"
    "BgNVHQ4EFgQU/jOS2yH3LuOyXByTQy6sF1U4gJcwHwYDVR0jBBgwFoAURBZWzhkT\n"
    "J5FITPVut2pmUz0RnEgwCgYIKoZIzj0EAwIDRgAwQwIgcx8P/wwx3eTiw9QbssZx\n"
    "Xhu5JR1RIoKJrdzuEIWGWQQCH1XO52anPbuPeWJWC6i+3iyalL48waXojy00ghVS\n"
    "0E4=\n"
    "-----END CERTIFICATE-----\n";

// SECC leaf private key for ISO 15118-2 (unencrypted EC key, secp256r1)
const char dev_private_key_pem_iso2[] =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MHcCAQEEIHh8JZH9DH2qLaVE2qNhw5Jg2j+LbZxAzb/Rg6lrqSqLoAoGCCqGSM49\n"
    "AwEHoUQDQgAE9vScGwavFc99Bt7u0Y3x+z2YxEluXPLYc6N7BXaXk55uvHSJD0Fy\n"
    "Ji4Kxrz+Us5nKJL6kdD8K9oqk7pCfthiNA==\n"
    "-----END EC PRIVATE KEY-----\n";

// =============================================================================
// ISO 15118-20 Certificates (secp521r1, TLS 1.3)
// =============================================================================
// [V2G20-2674] Primary: secp521r1 with ECDSA signature algorithm
// [V2G20-2675] Key length for ECC shall be 521 bit

const char dev_cert_chain_pem_iso20[] =
    // SECC Leaf Certificate
    "-----BEGIN CERTIFICATE-----\n"
    "MIICYDCCAcKgAwIBAgICV0wwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0EyMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjAyMDcyMDMyMjhaFw0yNjA0MDgyMDMyMjhaMEQxETAPBgNVBAMM\n"
    "CFNFQ0NDZXJ0MQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT\n"
    "8ixkARkWA0NQTzCBmzAQBgcqhkjOPQIBBgUrgQQAIwOBhgAEAZk3y1E80HBXBuar\n"
    "kkHgKfXvxHOwZrz8lOm46yNFvzp4L9aYM8Q2Jjy5rg7DwDpudaNzIegaoEmqjicf\n"
    "RIfEiAiYAb+Y2wGSK+DNu2FCtfbTT4z7nLoYSjRC6oeFKKSSAXpJ1xKsWi0rddnh\n"
    "ccJW1Oo4mtShnFj0mAMxO6mot8iTzab/o2AwXjAMBgNVHRMBAf8EAjAAMA4GA1Ud\n"
    "DwEB/wQEAwIDiDAdBgNVHQ4EFgQU6HcTa5Hx62WlyomUJvoGFEGredQwHwYDVR0j\n"
    "BBgwFoAUsAXZtLkGZfVqkw/InDmaTFBOGtkwCgYIKoZIzj0EAwIDgYsAMIGHAkFI\n"
    "1g++ldJ1svB6Q2rYjn0DsQZCDFkQDenOaaLjM2eEObkQ8O6+fWOO4JYRVZlYUNc1\n"
    "vObHyCImXi82hqj/QfiKowJCAWhL2fVKPO19sJFfvcZ/q+nhskorL8Yrk2AF4JtR\n"
    "InC6nTUx9y44j3maXj1zJ+LEVd8aiJpKY2Onn1WCtZ6JJSre\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 2
    "-----BEGIN CERTIFICATE-----\n"
    "MIICZzCCAcmgAwIBAgICV0swCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0ExMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjAyMDcyMDMyMjhaFw0yNzAyMDcyMDMyMjhaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMjENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAFXd4asY63Gt0Fb\n"
    "I89Hm5AsaslHI74ohVF954AOtsWBCJIXYc+t1e4RQQgUOVqgsdz8TvaOjQjjnZ/F\n"
    "bqUj0pRcLACduY7ouFGf9zyM+7hYk1+kzqnpci2+vKxtknHOoxspm0K+tn8+xfkL\n"
    "Aube/LLWKslXnwgWu8UAGyoej08Y3A+VgKNmMGQwEgYDVR0TAQH/BAgwBgEB/wIB\n"
    "ADAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFLAF2bS5BmX1apMPyJw5mkxQThrZ\n"
    "MB8GA1UdIwQYMBaAFFlgCKh3Rylzxogk71m2rduJvnlZMAoGCCqGSM49BAMCA4GL\n"
    "ADCBhwJBCTzGTzaTSN2FFwF+IykR0Hd5yn6uJdmsk6QcsfFozAGjHdMA640tBYdD\n"
    "e2r7HUVm0r6TsolksVnJv9cKgLkiIhICQgDNaxXYpRzf7UjPUYVkBdSm8wmDzfyC\n"
    "HDxxd3/dqjx/kL9rviPo3uGLEswahHIFOBTFRyFr4IwiR40CGlrUNzZAuQ==\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 1
    "-----BEGIN CERTIFICATE-----\n"
    "MIICZzCCAcmgAwIBAgICV0owCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjAyMDcyMDMyMjhaFw0zMDAyMDYyMDMyMjhaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABACfOqSXUuZGgheh\n"
    "ytzoOIUXgc9xAJo9JCVLNOLxh7KsimWa3wRE0OogLObinqWZbpIXNZtYEKob5q/B\n"
    "Xq+o3QoCUAC05x/nhRCkFTBW0OiMeoJjJWE43EkmlPB43960Fo3tplRqSzMLtUjV\n"
    "3Wu53q5Lt9wCTCj5eeHE2vJGSABGRKVJqqNmMGQwEgYDVR0TAQH/BAgwBgEB/wIB\n"
    "ATAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFFlgCKh3Rylzxogk71m2rduJvnlZ\n"
    "MB8GA1UdIwQYMBaAFK4tYiFvdDukoEWUQFd7yVskbqXtMAoGCCqGSM49BAMCA4GL\n"
    "ADCBhwJBJogk23XA9/KSxd47e2OPSH9bQ1WpCXWvJt14bPyk3X1f55bfJEPGo3d8\n"
    "oiWj3ylNhkb1HhRA7PqLjvHkvssEmLACQgDXQCd6ZVJgAGlUUjkPsxK/SXzRBAHr\n"
    "u/MDn9Wb9X9xTCxUCo9dWeMSXPD2C4LkZotoYXU3R0U02svC8pD2ck0dfA==\n"
    "-----END CERTIFICATE-----\n";

// SECC leaf private key for ISO 15118-20 (unencrypted EC key, secp521r1)
const char dev_private_key_pem_iso20[] =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MIHcAgEBBEIA9De9yXE9X3usgJuBGh2TH2bNeHv0vi33Cif5kPsp/FhmUwfgAmd1\n"
    "DaQYiLPNAfjhEEdXvpc6FZD0GQUhwJojfgagBwYFK4EEACOhgYkDgYYABAGZN8tR\n"
    "PNBwVwbmq5JB4Cn178RzsGa8/JTpuOsjRb86eC/WmDPENiY8ua4Ow8A6bnWjcyHo\n"
    "GqBJqo4nH0SHxIgImAG/mNsBkivgzbthQrX200+M+5y6GEo0QuqHhSikkgF6SdcS\n"
    "rFotK3XZ4XHCVtTqOJrUoZxY9JgDMTupqLfIk82m/w==\n"
    "-----END EC PRIVATE KEY-----\n";

// =============================================================================
// Trusted Root CA Certificates for Mutual TLS Authentication (ISO 15118-20)
// =============================================================================
// [V2G20-2400] SECC shall request EVCC certificate via CertificateRequest
// [V2G20-2338] SECC shall have at least one V2G or OEM root CA certificate
// These root CAs are used to verify the EVCC's vehicle certificate chain
// during the TLS 1.3 handshake (mutual authentication).

// OEM Root CA certificate (secp521r1): Trusts vehicle certificates
const char dev_oem_root_ca_pem_iso20[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICRTCCAaagAwIBAgIDAKVpMAoGCCqGSM49BAMCMEUxEjAQBgNVBAMMCU9FTVJv\n"
    "b3RDQTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJk/IsZAEZ\n"
    "FgNPRU0wHhcNMjYwMjA3MjAzMjI4WhcNMzYwMjA1MjAzMjI4WjBFMRIwEAYDVQQD\n"
    "DAlPRU1Sb290Q0ExDTALBgNVBAoMBFdBUlAxCzAJBgNVBAYTAkRFMRMwEQYKCZIm\n"
    "iZPyLGQBGRYDT0VNMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQASi7fOmLIEDC+\n"
    "GzLBXH81o4H6G+PWruWsUdYDdxhxBf5P2xLz1ITP9yKxnYHlUhJOr8oXpA5U7VYs\n"
    "WZdcVqzHEooBecvI0dZm+OO2zn+4XFC1/TLyFFHGzQ17ImyRbmKXWAAZNW7S4Rd7\n"
    "L3qbuoleMT527qfakaFx9bAIqFuPJgAmUu2jQjBAMA8GA1UdEwEB/wQFMAMBAf8w\n"
    "DgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBSKQRYoDwOhDxOBBKFxXcpuSL6sVjAK\n"
    "BggqhkjOPQQDAgOBjAAwgYgCQgDozvRCzxxns4uCu5QTNHLZENHgq3zhzA6VlZ3U\n"
    "28rWaN83UxguNb54VdUQwERU92L0E+rQRY1u/kRuNIiWvOr6NQJCAe15EQqAri0c\n"
    "Xg25X/0wiNaZQpiQjgDWjovNisPPbappzzIFM+/YXVnDOuXW8gdvF1u0tKerJVxb\n"
    "mylfC7lufXE/\n"
    "-----END CERTIFICATE-----\n";

// V2G Root CA certificate (secp521r1): Trusts SECC and contract certificates
const char dev_v2g_root_ca_pem_iso20[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICQzCCAaWgAwIBAgICV0kwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjAyMDcyMDMyMjhaFw0zNjAyMDUyMDMyMjhaMEUxEjAQBgNVBAMM\n"
    "CVYyR1Jvb3RDQTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABADypYNEegFH3Fnd\n"
    "Y3j90rFWucAToMqk6vzYt9klPIkZH3Daf7IKPJ2DOZgVPkp5fWVMxSX1TzNYVW1c\n"
    "6aBSI0LigAGqyg8k5xIw1xXmVl8Rq94PWG3JKaWQsS3eEsVQheZDlupd79SXfHZd\n"
    "Qs/LuPwa7VyhdfFBz5FUBIgbNQkmjo7VdaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAO\n"
    "BgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFK4tYiFvdDukoEWUQFd7yVskbqXtMAoG\n"
    "CCqGSM49BAMCA4GLADCBhwJBP273b/1xOZ2BxqReqQ7Mw1utuZHrJrtqCjtAYt9D\n"
    "CHxCC3PDaNLoiMehxgnYnIEat+TDki27ZQuJ5mzYRctKjR4CQgH1znwQ62Bq5zpE\n"
    "cxMZcsmIXovmTePyrRy9KY2us/NZ9w2cRZImeF3+pniOGXjEnO3u5DXa5EB8ylos\n"
    "t73H5OAOMQ==\n"
    "-----END CERTIFICATE-----\n";
