// WARNING: This file is generated by "src/modules/iso15118/tools/certs/generate_certs.sh"

// Embedded test certificates for development/testing
// Certificate chain: SECC Leaf -> CPO Sub-CA2 -> CPO Sub-CA1

#include "dev_certs.h"

#include "gcc_warnings.h"

// =============================================================================
// ISO 15118-2 Certificates (secp256r1/prime256v1, TLS 1.2)
// =============================================================================
// [V2G2-006] ECC-based using secp256r1 curve
// [V2G2-007] Key length for ECC shall be 256 bit

const char dev_cert_chain_pem_iso2[] =
    // SECC Leaf Certificate
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB2TCCAX+gAwIBAgICMDwwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0EyMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjYxMjEwMzlaFw0yNjEwMjUxMjEwMzlaMEQxETAPBgNVBAMM\n"
    "CFNFQ0NDZXJ0MQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT\n"
    "8ixkARkWA0NQTzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOOk+EWW1j2eA+zC\n"
    "gI2V+a2L7dW+yZiNz0xkzlmx8y8q+ZuKPAbDQGnWOykFZIFSC4buv8p7bmKfW0q5\n"
    "F/yt2iyjYDBeMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgOIMB0GA1UdDgQW\n"
    "BBQ7j/KBl5TvyQ0gnM/m/sV6JvlD3jAfBgNVHSMEGDAWgBTCg33cKnNJZXmn9Fzs\n"
    "i+UAi/ngnDAKBggqhkjOPQQDAgNIADBFAiEA2LwgnpFBrwgQwkfftYArhnZY2Fnx\n"
    "clPiiTPImA0KKPMCIHdeL5FTNPvtcwhohg1e5YRcEPM6zfyZwiMJWwKkx5fM\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 2
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB4DCCAYagAwIBAgICMDswCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0ExMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjYxMjEwMzlaFw0yNzA4MjYxMjEwMzlaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMjENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT5W09I03T8mtDl\n"
    "LwJAqNk3JqFRQD29CkNZUXTxCPYeVRbmuAFFKaw2HzpT/8SMOCb34+t8qZC8shFh\n"
    "HYDZ/Kb5o2YwZDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAd\n"
    "BgNVHQ4EFgQUwoN93CpzSWV5p/Rc7IvlAIv54JwwHwYDVR0jBBgwFoAUVxb6h1QC\n"
    "+Q7BelcqkuTUemJsS8UwCgYIKoZIzj0EAwIDSAAwRQIgegDCBpfQ88oy1Fdb3C8q\n"
    "W2rqzf6vtn2jtV/wG5zICiYCIQDotYspx4F98mlcj87vs4SmKU2C5k5YlMfylpJr\n"
    "nVW1XA==\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 1
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB4TCCAYagAwIBAgICMDowCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjYxMjEwMzlaFw0zMDA4MjUxMjEwMzlaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARqHyLAjQA9Ra+R\n"
    "LT0wwS1ASwOhgPTjW+CN1eF45UbsZaU+onymTJC27cxW0pX9XbORWZiAQQ0piNjS\n"
    "iGcw979Do2YwZDASBgNVHRMBAf8ECDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBBjAd\n"
    "BgNVHQ4EFgQUVxb6h1QC+Q7BelcqkuTUemJsS8UwHwYDVR0jBBgwFoAUvxFm8b5b\n"
    "6P6/v9IiRixw5CZEAygwCgYIKoZIzj0EAwIDSQAwRgIhAIe0E+FBoFKogT+Z5BQ5\n"
    "3bx9+qIubluY8FP82nFwHYM7AiEAnxXMmiwBhpnrZ/Cm7t4bICv08q6hdqjiisqd\n"
    "owLpBVU=\n"
    "-----END CERTIFICATE-----\n";

// SECC leaf private key for ISO 15118-2 (unencrypted EC key, secp256r1)
const char dev_private_key_pem_iso2[] =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MHcCAQEEIFpl1GQuc2VO7crEATenZBpbCj1ESUS3xmsbT/VUG/sCoAoGCCqGSM49\n"
    "AwEHoUQDQgAE46T4RZbWPZ4D7MKAjZX5rYvt1b7JmI3PTGTOWbHzLyr5m4o8BsNA\n"
    "adY7KQVkgVILhu6/yntuYp9bSrkX/K3aLA==\n"
    "-----END EC PRIVATE KEY-----\n";

// =============================================================================
// ISO 15118-20 Certificates (secp521r1, TLS 1.3)
// =============================================================================
// [V2G20-2674] Primary: secp521r1 with ECDSA signature algorithm
// [V2G20-2675] Key length for ECC shall be 521 bit

const char dev_cert_chain_pem_iso20[] =
    // SECC Leaf Certificate
    "-----BEGIN CERTIFICATE-----\n"
    "MIICYTCCAcKgAwIBAgICV0wwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0EyMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjYxMjEwNDBaFw0yNjEwMjUxMjEwNDBaMEQxETAPBgNVBAMM\n"
    "CFNFQ0NDZXJ0MQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT\n"
    "8ixkARkWA0NQTzCBmzAQBgcqhkjOPQIBBgUrgQQAIwOBhgAEAa6QhzFzfhAzgR/v\n"
    "9VqBojVmsWt1/aK1BsSqdqWcUeBjgJl/eIxOXJTVqEpFIwi7P3h/j9zHxZwqXfDz\n"
    "TrahlBaoAFunCALmLOMZ5McZN9xB7iJSD/WK1eeKPg+RnEum/gitJ0Cj9ayMYya3\n"
    "i7C+L01cwO26dlWdxQKGt3lpa0wA/CyGo2AwXjAMBgNVHRMBAf8EAjAAMA4GA1Ud\n"
    "DwEB/wQEAwIDiDAdBgNVHQ4EFgQUYu+lC1wsjEHk/g37rfNOBHDJ3JMwHwYDVR0j\n"
    "BBgwFoAUmSe1ohSl2tidYGl+9V2XRVQHKwUwCgYIKoZIzj0EAwIDgYwAMIGIAkIB\n"
    "paGqFW3uXtf5N/AEW6qylWp+dkatn8HUerNSALPeNixv7sGA6LGRgrxHYLM8qtzT\n"
    "laGlm9m49wzFMuIPLOF9/jECQgDVHomE2xY+WmjJDkjc9TTIregxLkQJiAcgGzDG\n"
    "sNwt7J14AlO54bb/7mdAYiH4tdPuZGi5BmqnZoOe6Q6TsM3I4g==\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 2
    "-----BEGIN CERTIFICATE-----\n"
    "MIICaDCCAcmgAwIBAgICV0swCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0ExMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjYxMjEwNDBaFw0yNzA4MjYxMjEwNDBaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMjENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAAXdIMhvJ7tKU9Y\n"
    "Fu/sC/RTClQS4GcB4HYuas3e8aCSKZXPN/o/j4wHz+zBKf8TVMwpgMYMVVOKGkVh\n"
    "bUV71y5m0gFK2+ES1Al5+l6FmHw/06DIXeyFiZMJ+ZcR76cMZ59fGIJK9WthvwRY\n"
    "2tyLjazIxg5L6RH2zJf1iB4ghm6vlk+gBKNmMGQwEgYDVR0TAQH/BAgwBgEB/wIB\n"
    "ADAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFJkntaIUpdrYnWBpfvVdl0VUBysF\n"
    "MB8GA1UdIwQYMBaAFNX+QPPaMsdQA0i6GSpc/cxmqbOVMAoGCCqGSM49BAMCA4GM\n"
    "ADCBiAJCAc6MtfUrFkK62RycYW2Yg969fMrwg6w12CQNpEOdtCUCILDLwCZpISSV\n"
    "KJREFwaQAynN1MqyzYV/7qNSZ971oWLhAkIAor1f3zNHz+JDtDwUDYxVofHWMdfL\n"
    "S5IxCXsSa4rPZCCSs0Qd7k00JUwfDXgX8aKxN/+ev6tX7XQ5punKB1vwDb8=\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 1
    "-----BEGIN CERTIFICATE-----\n"
    "MIICZzCCAcmgAwIBAgICV0owCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjYxMjEwNDBaFw0zMDA4MjUxMjEwNDBaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABABUsg9EWCzH36nD\n"
    "bcFwTjWLljnRM792+zSvTR9kpvIrfanrZuK6I9nb0Zk7m8v0xFrohnG7HyACak5q\n"
    "yYAVE+peKAB/vfwGogpNJSXLjfRs4a+SdpzrssQ9yE8sTcBciKX1GQWUuMWmPssF\n"
    "Oa0ZdnR6ncclrcPWpti8W5TYgU4HuCTLmqNmMGQwEgYDVR0TAQH/BAgwBgEB/wIB\n"
    "ATAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFNX+QPPaMsdQA0i6GSpc/cxmqbOV\n"
    "MB8GA1UdIwQYMBaAFFZg7KCZ8O2b68wwsV4WC2Ia7E8SMAoGCCqGSM49BAMCA4GL\n"
    "ADCBhwJBergrNUK1634lQ7HHrBFa8zTMoAsyBmzOiigclIThs2UIC2lyWoteXsR2\n"
    "iArUkQFaW6rxPHRtMfUVh3tY37e+rb0CQgGavpV3+NjDm8IDyriLAK61kJoC1eWI\n"
    "Z1hMntr/vS+jzUG8gewHsMQgtoRY9FpNnj5B1OjRtZ7H6wP+FOuyWYnulg==\n"
    "-----END CERTIFICATE-----\n";

// SECC leaf private key for ISO 15118-20 (unencrypted EC key, secp521r1)
const char dev_private_key_pem_iso20[] =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MIHcAgEBBEIBzswTRMRyV0chEJ/tC+Arm5ciZi4nuhZaZLSqdKVqwiIOfWniEdTN\n"
    "nW1AY1+8Nxyk1HhmPDuGYwSLeyiOqgwfH5agBwYFK4EEACOhgYkDgYYABAGukIcx\n"
    "c34QM4Ef7/VagaI1ZrFrdf2itQbEqnalnFHgY4CZf3iMTlyU1ahKRSMIuz94f4/c\n"
    "x8WcKl3w8062oZQWqABbpwgC5izjGeTHGTfcQe4iUg/1itXnij4PkZxLpv4IrSdA\n"
    "o/WsjGMmt4uwvi9NXMDtunZVncUChrd5aWtMAPwshg==\n"
    "-----END EC PRIVATE KEY-----\n";

// =============================================================================
// Trusted Root CA Certificates for Mutual TLS Authentication (ISO 15118-20)
// =============================================================================
// [V2G20-2400] SECC shall request EVCC certificate via CertificateRequest
// [V2G20-2338] SECC shall have at least one V2G or OEM root CA certificate
// These root CAs are used to verify the EVCC's vehicle certificate chain
// during the TLS 1.3 handshake (mutual authentication).

// OEM Root CA certificate (secp521r1): Trusts vehicle certificates
const char dev_oem_root_ca_pem_iso20[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICRTCCAaagAwIBAgIDAKVpMAoGCCqGSM49BAMCMEUxEjAQBgNVBAMMCU9FTVJv\n"
    "b3RDQTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJk/IsZAEZ\n"
    "FgNPRU0wHhcNMjYwODI2MTIxMDQwWhcNMzYwODIzMTIxMDQwWjBFMRIwEAYDVQQD\n"
    "DAlPRU1Sb290Q0ExDTALBgNVBAoMBFdBUlAxCzAJBgNVBAYTAkRFMRMwEQYKCZIm\n"
    "iZPyLGQBGRYDT0VNMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBExywx3Nn/Xd7\n"
    "we99h1uZEE26rLqpxCqafOUTgRR4UsCZ0HF0i4pJ31wKC23wcMoQ7GVsWLScDVcZ\n"
    "bxor8sLFdV8AgN7HlnI1W7KyG/cKBNGJ//0KLme7CG6Fkdv85a3y4vUHy4Uh4Fd4\n"
    "5EkY1m6HNPbBmrUZQJ+v/kxVjdFhFopVjfSjQjBAMA8GA1UdEwEB/wQFMAMBAf8w\n"
    "DgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBRmigDOJDupY23Xa0+zVsRZVL6E8TAK\n"
    "BggqhkjOPQQDAgOBjAAwgYgCQgHflUygC2RSMi3rU6y/jELHSb7nTAXQlXfUeJSx\n"
    "+HLZmkQLKWI/aAtUhO33ZuI71Ts3+dSCBjpgrOzihKg21iii2QJCAYOOwd5uxpa8\n"
    "jXCB/C1l2ryhRrp6mHIhznlFgbs27jsfuarCiqsSorlyW8aEJRx6AhUbr4n/vG+u\n"
    "GwVuKl+zAhJ2\n"
    "-----END CERTIFICATE-----\n";

// V2G Root CA certificate (secp521r1): Trusts SECC and contract certificates
const char dev_v2g_root_ca_pem_iso20[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICQzCCAaWgAwIBAgICV0kwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjYxMjEwNDBaFw0zNjA4MjMxMjEwNDBaMEUxEjAQBgNVBAMM\n"
    "CVYyR1Jvb3RDQTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAG5m6Ogiz/oDttx\n"
    "OHx9hn9YNv4W6fbGC967lr1/t1S24Ra7v5oMAm6sK768PZAcLqJo+vMq9kLB+88D\n"
    "28z+/YuzegEnhwngQaBtYfnfSECWvhhCDewyXZYfB/iq5+YGnUyD7KwIfo6fdo8J\n"
    "bA7oxEfFSXQYUhLmk+exhW5b/McAhzfL1aNCMEAwDwYDVR0TAQH/BAUwAwEB/zAO\n"
    "BgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFFZg7KCZ8O2b68wwsV4WC2Ia7E8SMAoG\n"
    "CCqGSM49BAMCA4GLADCBhwJBJzud8xsoXxwbV/oLF0GNJBQKce2DZsFCK3Xg3iuR\n"
    "FtkaIc7ybFq47Sg/DqQqWsCVifmqGFOyX3OA8Gs9YI3We0wCQgF30dVe3UMOrc1U\n"
    "9ocmqwvjg/nj9+yB6he5oMxpPkbedp43Her2paHhT5waZBg08/sI1N0PZSGzH8Pv\n"
    "6SLifwAIcw==\n"
    "-----END CERTIFICATE-----\n";
