// WARNING: This file is generated by "src/modules/iso15118/tools/certs/generate_certs.sh"

// Embedded test certificates for development/testing
// Certificate chain: SECC Leaf -> CPO Sub-CA2 -> CPO Sub-CA1

#include "dev_certs.h"
#include "options.h"

#include "gcc_warnings.h"

#if OPTIONS_ISO15118_DEV_CERTS_ENABLED()

// =============================================================================
// ISO 15118-2 Certificates (secp256r1/prime256v1, TLS 1.2)
// =============================================================================
// [V2G2-006] ECC-based using secp256r1 curve
// [V2G2-007] Key length for ECC shall be 256 bit

const char dev_cert_chain_pem_iso2[] =
    // SECC Leaf Certificate
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB2TCCAX+gAwIBAgICMDwwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0EyMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0yNjEwMjgyMTU4MDBaMEQxETAPBgNVBAMM\n"
    "CFNFQ0NDZXJ0MQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT\n"
    "8ixkARkWA0NQTzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGD5R6p74CVx74TY\n"
    "t9aIZzTQ46OFd4tHtqHtC4yNJAQN3S+TLmQt2mBwQ9kQ3X/ruR11kLT9jXLR4aPX\n"
    "ZBRRURSjYDBeMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgOIMB0GA1UdDgQW\n"
    "BBTHHgtHrTw2GxSwrFmUtpOQ2e/I+DAfBgNVHSMEGDAWgBSFK3vw4iMg33RCD2pr\n"
    "+j8uKlLtCzAKBggqhkjOPQQDAgNIADBFAiEAgW+atj327sulq/1weYkK31SNjbTO\n"
    "dCnxIepco5zsmxMCIGq8qVUxETv9FE/CoNIIP31EVdgi/3/vXW1Gi44hjZb/\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 2
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB4TCCAYagAwIBAgICMDswCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0ExMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0yNzA4MjkyMTU4MDBaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMjENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATeK1YlwcGPvkcb\n"
    "aWltxhf0aHJiT8wZzUI8dD6lZG5CWlYz6h/95FbjviC1lcHnU3NR84EnZbnKurUl\n"
    "LUKvTpEJo2YwZDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAd\n"
    "BgNVHQ4EFgQUhSt78OIjIN90Qg9qa/o/LipS7QswHwYDVR0jBBgwFoAUZuXUM+xc\n"
    "4WItu9K1wmMuK2yCMCswCgYIKoZIzj0EAwIDSQAwRgIhALYZLjdZ8uvg0ck+FPgt\n"
    "pkTllq3F7ClziAj4eB8zpL2SAiEAgJ5Kuo8gBIaIy33W4kpJ1vQUx/ktEnKMZxpY\n"
    "xEWkmVg=\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 1
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB4TCCAYagAwIBAgICMDowCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0zMDA4MjgyMTU4MDBaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASXFSA3rZ6+REAs\n"
    "1xyP/Bn2qvBlxBEAU0+Y5tSKXXJAOwf+J9SwZ8WrLYgCJ3iBTyYUZ+PAFRmdBjsg\n"
    "r2Xtl4Hso2YwZDASBgNVHRMBAf8ECDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBBjAd\n"
    "BgNVHQ4EFgQUZuXUM+xc4WItu9K1wmMuK2yCMCswHwYDVR0jBBgwFoAUKNImc0KV\n"
    "uU61uwbhy2EfB/YxUzgwCgYIKoZIzj0EAwIDSQAwRgIhAMqabfFoGi21Bc9po9qT\n"
    "CNFnxKAwmzmhdKtFcXXKQazDAiEAmkkrD3wweg+gB688oSEYXX6dptyKzEFsx/4A\n"
    "IFp6oSQ=\n"
    "-----END CERTIFICATE-----\n";

// SECC leaf private key for ISO 15118-2 (unencrypted EC key, secp256r1)
const char dev_private_key_pem_iso2[] =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MHcCAQEEIAJ8PFfc9dLpVb+wLdO/ZaurPrhi8ELR79ebkTy0uGOToAoGCCqGSM49\n"
    "AwEHoUQDQgAEYPlHqnvgJXHvhNi31ohnNNDjo4V3i0e2oe0LjI0kBA3dL5MuZC3a\n"
    "YHBD2RDdf+u5HXWQtP2NctHho9dkFFFRFA==\n"
    "-----END EC PRIVATE KEY-----\n";

// V2G Root CA anchoring the ISO 15118-2 development SECC chain
const char dev_v2g_root_ca_pem_iso2[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBvDCCAWKgAwIBAgICMDkwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0zNjA4MjYyMTU4MDBaMEUxEjAQBgNVBAMM\n"
    "CVYyR1Jvb3RDQTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARg98gif9Nzkc06\n"
    "Q3c43FLensa20tclcCgKfRmM33FLESGx9uZYyyguuCSBztIsVOSogigKZkJEIlq2\n"
    "+upaWpA2o0IwQDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV\n"
    "HQ4EFgQUKNImc0KVuU61uwbhy2EfB/YxUzgwCgYIKoZIzj0EAwIDSAAwRQIhAMwe\n"
    "maTPzwCMIyQ/3qN7XqK9F+UbGk6w1iv/9PEo64jAAiAM0dobNYhetQpkSmzSzvmr\n"
    "WxzVArcaREmOjy1JYQNbtw==\n"
    "-----END CERTIFICATE-----\n";

// =============================================================================
// ISO 15118-20 Certificates (secp521r1, TLS 1.3)
// =============================================================================
// [V2G20-2674] Primary: secp521r1 with ECDSA signature algorithm
// [V2G20-2675] Key length for ECC shall be 521 bit

const char dev_cert_chain_pem_iso20[] =
    // SECC Leaf Certificate
    "-----BEGIN CERTIFICATE-----\n"
    "MIICYDCCAcKgAwIBAgICV0wwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0EyMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0yNjEwMjgyMTU4MDBaMEQxETAPBgNVBAMM\n"
    "CFNFQ0NDZXJ0MQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT\n"
    "8ixkARkWA0NQTzCBmzAQBgcqhkjOPQIBBgUrgQQAIwOBhgAEADs5wemHe28AENJE\n"
    "xIUeeEissY6W2llu/cdRWRKhRukGPeHObdxm/I7GbRm/tyMX0mGGVMnAGRsNmkE/\n"
    "KhicE4LuAVkVR+PrEFsd6EdDBQc72NlBf8qOluwEoFM5MqgW2OaXuywhUfTCPYUZ\n"
    "UclWNayca4cUUD4G+66Az0wWFShLhhwUo2AwXjAMBgNVHRMBAf8EAjAAMA4GA1Ud\n"
    "DwEB/wQEAwIDiDAdBgNVHQ4EFgQUmM8h66IR/pnZr0gFaTtasGaWhAYwHwYDVR0j\n"
    "BBgwFoAUbGWk+z3YAFWr9h6ERXebsRc4WV4wCgYIKoZIzj0EAwIDgYsAMIGHAkIB\n"
    "mjtdzHfQ0/u3P5qGHEE6vjTW6VwTdeVpv8R1Fyhf/TQ/QnlIWF+IlNppoq2yYHWy\n"
    "uqBEZHFa9+7fVESGWn3l8F8CQSFRj+se4Hd4R3g+4PUAY6GLXbT2rwBHWj2mYY0e\n"
    "d0f9Dwi1Opgb9eI1GNy3FfXWdXqD75BSjTdAjvs136CWLZ0z\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 2
    "-----BEGIN CERTIFICATE-----\n"
    "MIICZjCCAcmgAwIBAgICV0swCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJQ1BPU3Vi\n"
    "Q0ExMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0yNzA4MjkyMTU4MDBaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMjENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAB5ZxzeSUPyy9gR\n"
    "zQpOkTK8GkYWE8B/sUZBZqERuWtgoxG9ND7tbgRl6t4BQBjwWYU9FqdYgRUPD4PV\n"
    "3kA/oLOfYAA2fhxX0MDGgIslyRl/P3qO4d3LJHEuMnZN/VGQTd5MMGJeMOmZk641\n"
    "Grw2vYo6crbcMiUVXxtQvKxUKUHwxxE1WqNmMGQwEgYDVR0TAQH/BAgwBgEB/wIB\n"
    "ADAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFGxlpPs92ABVq/YehEV3m7EXOFle\n"
    "MB8GA1UdIwQYMBaAFK54VbROsnApdBfwsWpKCYn3SsSYMAoGCCqGSM49BAMCA4GK\n"
    "ADCBhgJBEYhGCNhlH5t056F7Agfaho93oChp6cg37uai60NvZ5jetvQn8daVxNif\n"
    "jTOAmtxp1MfoBDoxqqOls4LR4piOA00CQTc29oAIUEsChjg5CTUlx6Y0LtX5QblO\n"
    "Jkyw/jyo3b5nrhQLfFZBNw/WCf0vVjmaF7vKxl7a+8+02xhXFwsicsoE\n"
    "-----END CERTIFICATE-----\n"
    // CPO Sub-CA 1
    "-----BEGIN CERTIFICATE-----\n"
    "MIICZjCCAcmgAwIBAgICV0owCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0zMDA4MjgyMTU4MDBaMEUxEjAQBgNVBAMM\n"
    "CUNQT1N1YkNBMTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAHcPPHCrRAIzUkp\n"
    "yPa2YCVnm1kRoeSCeipU00KmoooNDUmgI1jdeb4AQPnspQpApHazMQFzHpzLUFn7\n"
    "IeCQplqfvACFuQo7OFt7x4T2OFM0NMR1Z7nb2/Bq8cO42ekAya0+jwoleRqi7L17\n"
    "9NqU1NRD5wNIDC52fE0Fq2gKVym8rCv5l6NmMGQwEgYDVR0TAQH/BAgwBgEB/wIB\n"
    "ATAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFK54VbROsnApdBfwsWpKCYn3SsSY\n"
    "MB8GA1UdIwQYMBaAFPG95jYKpe3vDOH1YRaUt0nfDb8jMAoGCCqGSM49BAMCA4GK\n"
    "ADCBhgJBCW8Z9ggCrAbhnekV5kiyk/LyzQbjjow90vYufDxuDhfHHaQf5VA1lDka\n"
    "Vv0a9gMYErTfDsQEauxWQVJYz1zqxtcCQVinYy6elMvMvoojBHB3hGuXh2g29wLK\n"
    "bGWX4ycRWwsLF7W4XO6XoBF9UiXlsjmgF4yx2me6fPaSKJ7G2BAkhwaA\n"
    "-----END CERTIFICATE-----\n";

// SECC leaf private key for ISO 15118-20 (unencrypted EC key, secp521r1)
const char dev_private_key_pem_iso20[] =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MIHcAgEBBEIA7eWAmp9F3/SQRhTFXQLt0Himre0HCJT868GDwSgxVkUw3TMip48t\n"
    "4W+UvAiqwj8SSjf89L9rVP3pV9igeUXBTt2gBwYFK4EEACOhgYkDgYYABAA7OcHp\n"
    "h3tvABDSRMSFHnhIrLGOltpZbv3HUVkSoUbpBj3hzm3cZvyOxm0Zv7cjF9JhhlTJ\n"
    "wBkbDZpBPyoYnBOC7gFZFUfj6xBbHehHQwUHO9jZQX/KjpbsBKBTOTKoFtjml7ss\n"
    "IVH0wj2FGVHJVjWsnGuHFFA+BvuugM9MFhUoS4YcFA==\n"
    "-----END EC PRIVATE KEY-----\n";

// =============================================================================
// Trusted Root CA Certificates for Mutual TLS Authentication (ISO 15118-20)
// =============================================================================
// [V2G20-2400] SECC shall request EVCC certificate via CertificateRequest
// [V2G20-2338] SECC shall have at least one V2G or OEM root CA certificate
// These root CAs are used to verify the EVCC's vehicle certificate chain
// during the TLS 1.3 handshake (mutual authentication).

// OEM Root CA certificate (secp521r1): Trusts vehicle certificates
const char dev_oem_root_ca_pem_iso20[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICRTCCAaagAwIBAgIDAKVpMAoGCCqGSM49BAMCMEUxEjAQBgNVBAMMCU9FTVJv\n"
    "b3RDQTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJk/IsZAEZ\n"
    "FgNPRU0wHhcNMjYwODI5MjE1ODAwWhcNMzYwODI2MjE1ODAwWjBFMRIwEAYDVQQD\n"
    "DAlPRU1Sb290Q0ExDTALBgNVBAoMBFdBUlAxCzAJBgNVBAYTAkRFMRMwEQYKCZIm\n"
    "iZPyLGQBGRYDT0VNMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAI9uCAdxai056\n"
    "A7EGFfSr3ge+SEGTfQYYrj99Hbo/2HjYr+/tVW6DaWXtDz424O4sltYxCXhAu9ZO\n"
    "o/5600sQkm8ByCrN8S4c0OLUZ3sgMZexL5uUkWEb8slfeT/BF/rDlTruop+63tZK\n"
    "YMBfE3PlDBlxvsnvIB69dw79syOBLV/GH4KjQjBAMA8GA1UdEwEB/wQFMAMBAf8w\n"
    "DgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBSb1nw8DmMNTuK41zGigwSMk5lLDDAK\n"
    "BggqhkjOPQQDAgOBjAAwgYgCQgHY7RNaDrHYF91qktc/JDJ6hc5kAqZju7nhWLZS\n"
    "biKfxD8BIpLgfei6dFVIWeBLQXxNssBdpGYD1qFtJkP/HusSGwJCAJxHp57n3qjD\n"
    "xdzE1r/7rAsIcNJzcwU8usKeKVJ2Rmn5FgBWY5zdeBSRsR1POHtqd1WRv1cK1ajg\n"
    "IGzXjiD2Fl8X\n"
    "-----END CERTIFICATE-----\n";

// V2G Root CA certificate (secp521r1): Trusts SECC and contract certificates
const char dev_v2g_root_ca_pem_iso20[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICQjCCAaWgAwIBAgICV0kwCgYIKoZIzj0EAwIwRTESMBAGA1UEAwwJVjJHUm9v\n"
    "dENBMQ0wCwYDVQQKDARXQVJQMQswCQYDVQQGEwJERTETMBEGCgmSJomT8ixkARkW\n"
    "A1YyRzAeFw0yNjA4MjkyMTU4MDBaFw0zNjA4MjYyMTU4MDBaMEUxEjAQBgNVBAMM\n"
    "CVYyR1Jvb3RDQTENMAsGA1UECgwEV0FSUDELMAkGA1UEBhMCREUxEzARBgoJkiaJ\n"
    "k/IsZAEZFgNWMkcwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAAkg8JqV/PDJXJ1\n"
    "cJlCOyvwQLu5eMSJPCSiEY3jFidL6Gj+P+kRGhVlkyx9gsOcLPkYW3qcyKHKlBoX\n"
    "e+t2E/VwmQGrM7mOyy88AjoooWkTIu7Nm2UIOiwfUx+h+lznFhgOU4MAJHdHYA8a\n"
    "KQu09d+xJgDtLChfDZkEVUWsr2W7M33R2KNCMEAwDwYDVR0TAQH/BAUwAwEB/zAO\n"
    "BgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFPG95jYKpe3vDOH1YRaUt0nfDb8jMAoG\n"
    "CCqGSM49BAMCA4GKADCBhgJBNIjUrQ03dbWoHpj3pV61r6o6fdunbXbm17BJJVn/\n"
    "/eG1Qk2OelvqAtHU3qxxcTpMkkLjh1LvpcktGuehV9llQA0CQRJP1W9Y47RM1s8Z\n"
    "JUkFSUpU781Q9sKWyuR5+0hcG+hsWMs6BEIrBhYA1z6NvP91uYNdvcgEieChxsMS\n"
    "ngdrsseU\n"
    "-----END CERTIFICATE-----\n";

#endif
