// Don't edit this file. It is automatically generated by make_flash_map.py.

#pragma once

#define METADATA_VERSION  0x00000001U
#define METADATA_LENGTH   0x000C2A00U
#define METADATA_CHECKSUM 0xFDE50FA2U
