/*
2024b;2024-09-10T09:51:57.237946
*/
/* esp32-firmware
 * Copyright (C) 2020-2021 Erik Fleckstein <erik@tinkerforge.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include "timezone_translation.h"

static const char * const Africa_keys[] = {
    "Abidjan",
    "Accra",
    "Addis_Ababa",
    "Algiers",
    "Asmara",
    "Asmera",
    "Bamako",
    "Bangui",
    "Banjul",
    "Bissau",
    "Blantyre",
    "Brazzaville",
    "Bujumbura",
    "Cairo",
    "Casablanca",
    "Ceuta",
    "Conakry",
    "Dakar",
    "Dar_es_Salaam",
    "Djibouti",
    "Douala",
    "El_Aaiun",
    "Freetown",
    "Gaborone",
    "Harare",
    "Johannesburg",
    "Juba",
    "Kampala",
    "Khartoum",
    "Kigali",
    "Kinshasa",
    "Lagos",
    "Libreville",
    "Lome",
    "Luanda",
    "Lubumbashi",
    "Lusaka",
    "Malabo",
    "Maputo",
    "Maseru",
    "Mbabane",
    "Mogadishu",
    "Monrovia",
    "Nairobi",
    "Ndjamena",
    "Niamey",
    "Nouakchott",
    "Ouagadougou",
    "Porto-Novo",
    "Sao_Tome",
    "Timbuktu",
    "Tripoli",
    "Tunis",
    "Windhoek"
};

static const TableValue Africa_vals[] = {
    {true, {"GMT0"}},
    {true, {"GMT0"}},
    {true, {"EAT-3"}},
    {true, {"CET-1"}},
    {true, {"EAT-3"}},
    {true, {"EAT-3"}},
    {true, {"GMT0"}},
    {true, {"WAT-1"}},
    {true, {"GMT0"}},
    {true, {"GMT0"}},
    {true, {"CAT-2"}},
    {true, {"WAT-1"}},
    {true, {"CAT-2"}},
    {true, {"EET-2EEST,M4.5.5/0,M10.5.4/24"}},
    {true, {"<+01>-1"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"GMT0"}},
    {true, {"GMT0"}},
    {true, {"EAT-3"}},
    {true, {"EAT-3"}},
    {true, {"WAT-1"}},
    {true, {"<+01>-1"}},
    {true, {"GMT0"}},
    {true, {"CAT-2"}},
    {true, {"CAT-2"}},
    {true, {"SAST-2"}},
    {true, {"CAT-2"}},
    {true, {"EAT-3"}},
    {true, {"CAT-2"}},
    {true, {"CAT-2"}},
    {true, {"WAT-1"}},
    {true, {"WAT-1"}},
    {true, {"WAT-1"}},
    {true, {"GMT0"}},
    {true, {"WAT-1"}},
    {true, {"CAT-2"}},
    {true, {"CAT-2"}},
    {true, {"WAT-1"}},
    {true, {"CAT-2"}},
    {true, {"SAST-2"}},
    {true, {"SAST-2"}},
    {true, {"EAT-3"}},
    {true, {"GMT0"}},
    {true, {"EAT-3"}},
    {true, {"WAT-1"}},
    {true, {"WAT-1"}},
    {true, {"GMT0"}},
    {true, {"GMT0"}},
    {true, {"WAT-1"}},
    {true, {"GMT0"}},
    {true, {"GMT0"}},
    {true, {"EET-2"}},
    {true, {"CET-1"}},
    {true, {"CAT-2"}},
};

static const Table Africa = {Africa_keys, Africa_vals, 54};

static const char * const Argentina_keys[] = {
    "Buenos_Aires",
    "Catamarca",
    "ComodRivadavia",
    "Cordoba",
    "Jujuy",
    "La_Rioja",
    "Mendoza",
    "Rio_Gallegos",
    "Salta",
    "San_Juan",
    "San_Luis",
    "Tucuman",
    "Ushuaia"
};

static const TableValue Argentina_vals[] = {
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
};

static const Table Argentina = {Argentina_keys, Argentina_vals, 13};

static const char * const Indiana_keys[] = {
    "Indianapolis",
    "Knox",
    "Marengo",
    "Petersburg",
    "Tell_City",
    "Vevay",
    "Vincennes",
    "Winamac"
};

static const TableValue Indiana_vals[] = {
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
};

static const Table Indiana = {Indiana_keys, Indiana_vals, 8};

static const char * const Kentucky_keys[] = {
    "Louisville",
    "Monticello"
};

static const TableValue Kentucky_vals[] = {
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
};

static const Table Kentucky = {Kentucky_keys, Kentucky_vals, 2};

static const char * const North_Dakota_keys[] = {
    "Beulah",
    "Center",
    "New_Salem"
};

static const TableValue North_Dakota_vals[] = {
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
};

static const Table North_Dakota = {North_Dakota_keys, North_Dakota_vals, 3};

static const char * const America_keys[] = {
    "Adak",
    "Anchorage",
    "Anguilla",
    "Antigua",
    "Araguaina",
    "Argentina",
    "Aruba",
    "Asuncion",
    "Atikokan",
    "Atka",
    "Bahia",
    "Bahia_Banderas",
    "Barbados",
    "Belem",
    "Belize",
    "Blanc-Sablon",
    "Boa_Vista",
    "Bogota",
    "Boise",
    "Buenos_Aires",
    "Cambridge_Bay",
    "Campo_Grande",
    "Cancun",
    "Caracas",
    "Catamarca",
    "Cayenne",
    "Cayman",
    "Chicago",
    "Chihuahua",
    "Ciudad_Juarez",
    "Coral_Harbour",
    "Cordoba",
    "Costa_Rica",
    "Creston",
    "Cuiaba",
    "Curacao",
    "Danmarkshavn",
    "Dawson",
    "Dawson_Creek",
    "Denver",
    "Detroit",
    "Dominica",
    "Edmonton",
    "Eirunepe",
    "El_Salvador",
    "Ensenada",
    "Fort_Nelson",
    "Fort_Wayne",
    "Fortaleza",
    "Glace_Bay",
    "Godthab",
    "Goose_Bay",
    "Grand_Turk",
    "Grenada",
    "Guadeloupe",
    "Guatemala",
    "Guayaquil",
    "Guyana",
    "Halifax",
    "Havana",
    "Hermosillo",
    "Indiana",
    "Indianapolis",
    "Inuvik",
    "Iqaluit",
    "Jamaica",
    "Jujuy",
    "Juneau",
    "Kentucky",
    "Knox_IN",
    "Kralendijk",
    "La_Paz",
    "Lima",
    "Los_Angeles",
    "Louisville",
    "Lower_Princes",
    "Maceio",
    "Managua",
    "Manaus",
    "Marigot",
    "Martinique",
    "Matamoros",
    "Mazatlan",
    "Mendoza",
    "Menominee",
    "Merida",
    "Metlakatla",
    "Mexico_City",
    "Miquelon",
    "Moncton",
    "Monterrey",
    "Montevideo",
    "Montreal",
    "Montserrat",
    "Nassau",
    "New_York",
    "Nipigon",
    "Nome",
    "Noronha",
    "North_Dakota",
    "Nuuk",
    "Ojinaga",
    "Panama",
    "Pangnirtung",
    "Paramaribo",
    "Phoenix",
    "Port-au-Prince",
    "Port_of_Spain",
    "Porto_Acre",
    "Porto_Velho",
    "Puerto_Rico",
    "Punta_Arenas",
    "Rainy_River",
    "Rankin_Inlet",
    "Recife",
    "Regina",
    "Resolute",
    "Rio_Branco",
    "Rosario",
    "Santa_Isabel",
    "Santarem",
    "Santiago",
    "Santo_Domingo",
    "Sao_Paulo",
    "Scoresbysund",
    "Shiprock",
    "Sitka",
    "St_Barthelemy",
    "St_Johns",
    "St_Kitts",
    "St_Lucia",
    "St_Thomas",
    "St_Vincent",
    "Swift_Current",
    "Tegucigalpa",
    "Thule",
    "Thunder_Bay",
    "Tijuana",
    "Toronto",
    "Tortola",
    "Vancouver",
    "Virgin",
    "Whitehorse",
    "Winnipeg",
    "Yakutat",
    "Yellowknife"
};

static const TableValue America_vals[] = {
    {true, {"HST10HDT,M3.2.0,M11.1.0"}},
    {true, {"AKST9AKDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"AST4"}},
    {true, {"<-03>3"}},
    {false, {.sub_table=&Argentina}},
    {true, {"AST4"}},
    {true, {"<-04>4<-03>,M10.1.0/0,M3.4.0/0"}},
    {true, {"EST5"}},
    {true, {"HST10HDT,M3.2.0,M11.1.0"}},
    {true, {"<-03>3"}},
    {true, {"CST6"}},
    {true, {"AST4"}},
    {true, {"<-03>3"}},
    {true, {"CST6"}},
    {true, {"AST4"}},
    {true, {"<-04>4"}},
    {true, {"<-05>5"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
    {true, {"<-03>3"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
    {true, {"<-04>4"}},
    {true, {"EST5"}},
    {true, {"<-04>4"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"EST5"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"CST6"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
    {true, {"EST5"}},
    {true, {"<-03>3"}},
    {true, {"CST6"}},
    {true, {"MST7"}},
    {true, {"<-04>4"}},
    {true, {"AST4"}},
    {true, {"GMT0"}},
    {true, {"MST7"}},
    {true, {"MST7"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
    {true, {"<-05>5"}},
    {true, {"CST6"}},
    {true, {"PST8PDT,M3.2.0,M11.1.0"}},
    {true, {"MST7"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"<-03>3"}},
    {true, {"AST4ADT,M3.2.0,M11.1.0"}},
    {true, {"<-02>2<-01>,M3.5.0/-1,M10.5.0/0"}},
    {true, {"AST4ADT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"AST4"}},
    {true, {"CST6"}},
    {true, {"<-05>5"}},
    {true, {"<-04>4"}},
    {true, {"AST4ADT,M3.2.0,M11.1.0"}},
    {true, {"CST5CDT,M3.2.0/0,M11.1.0/1"}},
    {true, {"MST7"}},
    {false, {.sub_table=&Indiana}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"EST5"}},
    {true, {"<-03>3"}},
    {true, {"AKST9AKDT,M3.2.0,M11.1.0"}},
    {false, {.sub_table=&Kentucky}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"<-04>4"}},
    {true, {"<-05>5"}},
    {true, {"PST8PDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"<-03>3"}},
    {true, {"CST6"}},
    {true, {"<-04>4"}},
    {true, {"AST4"}},
    {true, {"AST4"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"MST7"}},
    {true, {"<-03>3"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"CST6"}},
    {true, {"AKST9AKDT,M3.2.0,M11.1.0"}},
    {true, {"CST6"}},
    {true, {"<-03>3<-02>,M3.2.0,M11.1.0"}},
    {true, {"AST4ADT,M3.2.0,M11.1.0"}},
    {true, {"CST6"}},
    {true, {"<-03>3"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"AKST9AKDT,M3.2.0,M11.1.0"}},
    {true, {"<-02>2"}},
    {false, {.sub_table=&North_Dakota}},
    {true, {"<-02>2<-01>,M3.5.0/-1,M10.5.0/0"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"EST5"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"<-03>3"}},
    {true, {"MST7"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"<-05>5"}},
    {true, {"<-04>4"}},
    {true, {"AST4"}},
    {true, {"<-03>3"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"<-03>3"}},
    {true, {"CST6"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"<-05>5"}},
    {true, {"<-03>3"}},
    {true, {"PST8PDT,M3.2.0,M11.1.0"}},
    {true, {"<-03>3"}},
    {true, {"<-04>4<-03>,M9.1.6/24,M4.1.6/24"}},
    {true, {"AST4"}},
    {true, {"<-03>3"}},
    {true, {"<-02>2<-01>,M3.5.0/-1,M10.5.0/0"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
    {true, {"AKST9AKDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"NST3:30NDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"AST4"}},
    {true, {"AST4"}},
    {true, {"AST4"}},
    {true, {"CST6"}},
    {true, {"CST6"}},
    {true, {"AST4ADT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"PST8PDT,M3.2.0,M11.1.0"}},
    {true, {"EST5EDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"PST8PDT,M3.2.0,M11.1.0"}},
    {true, {"AST4"}},
    {true, {"MST7"}},
    {true, {"CST6CDT,M3.2.0,M11.1.0"}},
    {true, {"AKST9AKDT,M3.2.0,M11.1.0"}},
    {true, {"MST7MDT,M3.2.0,M11.1.0"}},
};

static const Table America = {America_keys, America_vals, 146};

static const char * const Antarctica_keys[] = {
    "Casey",
    "Davis",
    "DumontDUrville",
    "Macquarie",
    "Mawson",
    "McMurdo",
    "Palmer",
    "Rothera",
    "South_Pole",
    "Syowa",
    "Troll",
    "Vostok"
};

static const TableValue Antarctica_vals[] = {
    {true, {"<+08>-8"}},
    {true, {"<+07>-7"}},
    {true, {"<+10>-10"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"<+05>-5"}},
    {true, {"NZST-12NZDT,M9.5.0,M4.1.0/3"}},
    {true, {"<-03>3"}},
    {true, {"<-03>3"}},
    {true, {"NZST-12NZDT,M9.5.0,M4.1.0/3"}},
    {true, {"<+03>-3"}},
    {true, {"<+00>0<+02>-2,M3.5.0/1,M10.5.0/3"}},
    {true, {"<+05>-5"}},
};

static const Table Antarctica = {Antarctica_keys, Antarctica_vals, 12};

static const char * const Arctic_keys[] = {
    "Longyearbyen"
};

static const TableValue Arctic_vals[] = {
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
};

static const Table Arctic = {Arctic_keys, Arctic_vals, 1};

static const char * const Asia_keys[] = {
    "Aden",
    "Almaty",
    "Amman",
    "Anadyr",
    "Aqtau",
    "Aqtobe",
    "Ashgabat",
    "Ashkhabad",
    "Atyrau",
    "Baghdad",
    "Bahrain",
    "Baku",
    "Bangkok",
    "Barnaul",
    "Beirut",
    "Bishkek",
    "Brunei",
    "Calcutta",
    "Chita",
    "Choibalsan",
    "Chongqing",
    "Chungking",
    "Colombo",
    "Dacca",
    "Damascus",
    "Dhaka",
    "Dili",
    "Dubai",
    "Dushanbe",
    "Famagusta",
    "Gaza",
    "Harbin",
    "Hebron",
    "Ho_Chi_Minh",
    "Hong_Kong",
    "Hovd",
    "Irkutsk",
    "Istanbul",
    "Jakarta",
    "Jayapura",
    "Jerusalem",
    "Kabul",
    "Kamchatka",
    "Karachi",
    "Kashgar",
    "Kathmandu",
    "Katmandu",
    "Khandyga",
    "Kolkata",
    "Krasnoyarsk",
    "Kuala_Lumpur",
    "Kuching",
    "Kuwait",
    "Macao",
    "Macau",
    "Magadan",
    "Makassar",
    "Manila",
    "Muscat",
    "Nicosia",
    "Novokuznetsk",
    "Novosibirsk",
    "Omsk",
    "Oral",
    "Phnom_Penh",
    "Pontianak",
    "Pyongyang",
    "Qatar",
    "Qostanay",
    "Qyzylorda",
    "Rangoon",
    "Riyadh",
    "Saigon",
    "Sakhalin",
    "Samarkand",
    "Seoul",
    "Shanghai",
    "Singapore",
    "Srednekolymsk",
    "Taipei",
    "Tashkent",
    "Tbilisi",
    "Tehran",
    "Tel_Aviv",
    "Thimbu",
    "Thimphu",
    "Tokyo",
    "Tomsk",
    "Ujung_Pandang",
    "Ulaanbaatar",
    "Ulan_Bator",
    "Urumqi",
    "Ust-Nera",
    "Vientiane",
    "Vladivostok",
    "Yakutsk",
    "Yangon",
    "Yekaterinburg",
    "Yerevan"
};

static const TableValue Asia_vals[] = {
    {true, {"<+03>-3"}},
    {true, {"<+05>-5"}},
    {true, {"<+03>-3"}},
    {true, {"<+12>-12"}},
    {true, {"<+05>-5"}},
    {true, {"<+05>-5"}},
    {true, {"<+05>-5"}},
    {true, {"<+05>-5"}},
    {true, {"<+05>-5"}},
    {true, {"<+03>-3"}},
    {true, {"<+03>-3"}},
    {true, {"<+04>-4"}},
    {true, {"<+07>-7"}},
    {true, {"<+07>-7"}},
    {true, {"EET-2EEST,M3.5.0/0,M10.5.0/0"}},
    {true, {"<+06>-6"}},
    {true, {"<+08>-8"}},
    {true, {"IST-5:30"}},
    {true, {"<+09>-9"}},
    {true, {"<+08>-8"}},
    {true, {"CST-8"}},
    {true, {"CST-8"}},
    {true, {"<+0530>-5:30"}},
    {true, {"<+06>-6"}},
    {true, {"<+03>-3"}},
    {true, {"<+06>-6"}},
    {true, {"<+09>-9"}},
    {true, {"<+04>-4"}},
    {true, {"<+05>-5"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"EET-2EEST,M3.4.4/50,M10.4.4/50"}},
    {true, {"CST-8"}},
    {true, {"EET-2EEST,M3.4.4/50,M10.4.4/50"}},
    {true, {"<+07>-7"}},
    {true, {"HKT-8"}},
    {true, {"<+07>-7"}},
    {true, {"<+08>-8"}},
    {true, {"<+03>-3"}},
    {true, {"WIB-7"}},
    {true, {"WIT-9"}},
    {true, {"IST-2IDT,M3.4.4/26,M10.5.0"}},
    {true, {"<+0430>-4:30"}},
    {true, {"<+12>-12"}},
    {true, {"PKT-5"}},
    {true, {"<+06>-6"}},
    {true, {"<+0545>-5:45"}},
    {true, {"<+0545>-5:45"}},
    {true, {"<+09>-9"}},
    {true, {"IST-5:30"}},
    {true, {"<+07>-7"}},
    {true, {"<+08>-8"}},
    {true, {"<+08>-8"}},
    {true, {"<+03>-3"}},
    {true, {"CST-8"}},
    {true, {"CST-8"}},
    {true, {"<+11>-11"}},
    {true, {"WITA-8"}},
    {true, {"PST-8"}},
    {true, {"<+04>-4"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"<+07>-7"}},
    {true, {"<+07>-7"}},
    {true, {"<+06>-6"}},
    {true, {"<+05>-5"}},
    {true, {"<+07>-7"}},
    {true, {"WIB-7"}},
    {true, {"KST-9"}},
    {true, {"<+03>-3"}},
    {true, {"<+05>-5"}},
    {true, {"<+05>-5"}},
    {true, {"<+0630>-6:30"}},
    {true, {"<+03>-3"}},
    {true, {"<+07>-7"}},
    {true, {"<+11>-11"}},
    {true, {"<+05>-5"}},
    {true, {"KST-9"}},
    {true, {"CST-8"}},
    {true, {"<+08>-8"}},
    {true, {"<+11>-11"}},
    {true, {"CST-8"}},
    {true, {"<+05>-5"}},
    {true, {"<+04>-4"}},
    {true, {"<+0330>-3:30"}},
    {true, {"IST-2IDT,M3.4.4/26,M10.5.0"}},
    {true, {"<+06>-6"}},
    {true, {"<+06>-6"}},
    {true, {"JST-9"}},
    {true, {"<+07>-7"}},
    {true, {"WITA-8"}},
    {true, {"<+08>-8"}},
    {true, {"<+08>-8"}},
    {true, {"<+06>-6"}},
    {true, {"<+10>-10"}},
    {true, {"<+07>-7"}},
    {true, {"<+10>-10"}},
    {true, {"<+09>-9"}},
    {true, {"<+0630>-6:30"}},
    {true, {"<+05>-5"}},
    {true, {"<+04>-4"}},
};

static const Table Asia = {Asia_keys, Asia_vals, 99};

static const char * const Atlantic_keys[] = {
    "Azores",
    "Bermuda",
    "Canary",
    "Cape_Verde",
    "Faeroe",
    "Faroe",
    "Jan_Mayen",
    "Madeira",
    "Reykjavik",
    "South_Georgia",
    "St_Helena",
    "Stanley"
};

static const TableValue Atlantic_vals[] = {
    {true, {"<-01>1<+00>,M3.5.0/0,M10.5.0/1"}},
    {true, {"AST4ADT,M3.2.0,M11.1.0"}},
    {true, {"WET0WEST,M3.5.0/1,M10.5.0"}},
    {true, {"<-01>1"}},
    {true, {"WET0WEST,M3.5.0/1,M10.5.0"}},
    {true, {"WET0WEST,M3.5.0/1,M10.5.0"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"WET0WEST,M3.5.0/1,M10.5.0"}},
    {true, {"GMT0"}},
    {true, {"<-02>2"}},
    {true, {"GMT0"}},
    {true, {"<-03>3"}},
};

static const Table Atlantic = {Atlantic_keys, Atlantic_vals, 12};

static const char * const Australia_keys[] = {
    "ACT",
    "Adelaide",
    "Brisbane",
    "Broken_Hill",
    "Canberra",
    "Currie",
    "Darwin",
    "Eucla",
    "Hobart",
    "LHI",
    "Lindeman",
    "Lord_Howe",
    "Melbourne",
    "NSW",
    "North",
    "Perth",
    "Queensland",
    "South",
    "Sydney",
    "Tasmania",
    "Victoria",
    "West",
    "Yancowinna"
};

static const TableValue Australia_vals[] = {
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"ACST-9:30ACDT,M10.1.0,M4.1.0/3"}},
    {true, {"AEST-10"}},
    {true, {"ACST-9:30ACDT,M10.1.0,M4.1.0/3"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"ACST-9:30"}},
    {true, {"<+0845>-8:45"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"<+1030>-10:30<+11>-11,M10.1.0,M4.1.0"}},
    {true, {"AEST-10"}},
    {true, {"<+1030>-10:30<+11>-11,M10.1.0,M4.1.0"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"ACST-9:30"}},
    {true, {"AWST-8"}},
    {true, {"AEST-10"}},
    {true, {"ACST-9:30ACDT,M10.1.0,M4.1.0/3"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"AEST-10AEDT,M10.1.0,M4.1.0/3"}},
    {true, {"AWST-8"}},
    {true, {"ACST-9:30ACDT,M10.1.0,M4.1.0/3"}},
};

static const Table Australia = {Australia_keys, Australia_vals, 23};

static const char * const Etc_keys[] = {
    "GMT",
    "GMT+0",
    "GMT+1",
    "GMT+10",
    "GMT+11",
    "GMT+12",
    "GMT+2",
    "GMT+3",
    "GMT+4",
    "GMT+5",
    "GMT+6",
    "GMT+7",
    "GMT+8",
    "GMT+9",
    "GMT-0",
    "GMT-1",
    "GMT-10",
    "GMT-11",
    "GMT-12",
    "GMT-13",
    "GMT-14",
    "GMT-2",
    "GMT-3",
    "GMT-4",
    "GMT-5",
    "GMT-6",
    "GMT-7",
    "GMT-8",
    "GMT-9",
    "GMT0",
    "Greenwich",
    "UCT",
    "UTC",
    "Universal",
    "Zulu"
};

static const TableValue Etc_vals[] = {
    {true, {"GMT0"}},
    {true, {"GMT0"}},
    {true, {"<-01>1"}},
    {true, {"<-10>10"}},
    {true, {"<-11>11"}},
    {true, {"<-12>12"}},
    {true, {"<-02>2"}},
    {true, {"<-03>3"}},
    {true, {"<-04>4"}},
    {true, {"<-05>5"}},
    {true, {"<-06>6"}},
    {true, {"<-07>7"}},
    {true, {"<-08>8"}},
    {true, {"<-09>9"}},
    {true, {"GMT0"}},
    {true, {"<+01>-1"}},
    {true, {"<+10>-10"}},
    {true, {"<+11>-11"}},
    {true, {"<+12>-12"}},
    {true, {"<+13>-13"}},
    {true, {"<+14>-14"}},
    {true, {"<+02>-2"}},
    {true, {"<+03>-3"}},
    {true, {"<+04>-4"}},
    {true, {"<+05>-5"}},
    {true, {"<+06>-6"}},
    {true, {"<+07>-7"}},
    {true, {"<+08>-8"}},
    {true, {"<+09>-9"}},
    {true, {"GMT0"}},
    {true, {"GMT0"}},
    {true, {"UTC0"}},
    {true, {"UTC0"}},
    {true, {"UTC0"}},
    {true, {"UTC0"}},
};

static const Table Etc = {Etc_keys, Etc_vals, 35};

static const char * const Europe_keys[] = {
    "Amsterdam",
    "Andorra",
    "Astrakhan",
    "Athens",
    "Belfast",
    "Belgrade",
    "Berlin",
    "Bratislava",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Busingen",
    "Chisinau",
    "Copenhagen",
    "Dublin",
    "Gibraltar",
    "Guernsey",
    "Helsinki",
    "Isle_of_Man",
    "Istanbul",
    "Jersey",
    "Kaliningrad",
    "Kiev",
    "Kirov",
    "Kyiv",
    "Lisbon",
    "Ljubljana",
    "London",
    "Luxembourg",
    "Madrid",
    "Malta",
    "Mariehamn",
    "Minsk",
    "Monaco",
    "Moscow",
    "Nicosia",
    "Oslo",
    "Paris",
    "Podgorica",
    "Prague",
    "Riga",
    "Rome",
    "Samara",
    "San_Marino",
    "Sarajevo",
    "Saratov",
    "Simferopol",
    "Skopje",
    "Sofia",
    "Stockholm",
    "Tallinn",
    "Tirane",
    "Tiraspol",
    "Ulyanovsk",
    "Uzhgorod",
    "Vaduz",
    "Vatican",
    "Vienna",
    "Vilnius",
    "Volgograd",
    "Warsaw",
    "Zagreb",
    "Zaporozhye",
    "Zurich"
};

static const TableValue Europe_vals[] = {
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"<+04>-4"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"GMT0BST,M3.5.0/1,M10.5.0"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"IST-1GMT0,M10.5.0,M3.5.0/1"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"GMT0BST,M3.5.0/1,M10.5.0"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"GMT0BST,M3.5.0/1,M10.5.0"}},
    {true, {"<+03>-3"}},
    {true, {"GMT0BST,M3.5.0/1,M10.5.0"}},
    {true, {"EET-2"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"MSK-3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"WET0WEST,M3.5.0/1,M10.5.0"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"GMT0BST,M3.5.0/1,M10.5.0"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"<+03>-3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"MSK-3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"<+04>-4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"<+04>-4"}},
    {true, {"MSK-3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0,M10.5.0/3"}},
    {true, {"<+04>-4"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"MSK-3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
    {true, {"EET-2EEST,M3.5.0/3,M10.5.0/4"}},
    {true, {"CET-1CEST,M3.5.0,M10.5.0/3"}},
};

static const Table Europe = {Europe_keys, Europe_vals, 64};

static const char * const Indian_keys[] = {
    "Antananarivo",
    "Chagos",
    "Christmas",
    "Cocos",
    "Comoro",
    "Kerguelen",
    "Mahe",
    "Maldives",
    "Mauritius",
    "Mayotte",
    "Reunion"
};

static const TableValue Indian_vals[] = {
    {true, {"EAT-3"}},
    {true, {"<+06>-6"}},
    {true, {"<+07>-7"}},
    {true, {"<+0630>-6:30"}},
    {true, {"EAT-3"}},
    {true, {"<+05>-5"}},
    {true, {"<+04>-4"}},
    {true, {"<+05>-5"}},
    {true, {"<+04>-4"}},
    {true, {"EAT-3"}},
    {true, {"<+04>-4"}},
};

static const Table Indian = {Indian_keys, Indian_vals, 11};

static const char * const Pacific_keys[] = {
    "Apia",
    "Auckland",
    "Bougainville",
    "Chatham",
    "Chuuk",
    "Easter",
    "Efate",
    "Enderbury",
    "Fakaofo",
    "Fiji",
    "Funafuti",
    "Galapagos",
    "Gambier",
    "Guadalcanal",
    "Guam",
    "Honolulu",
    "Johnston",
    "Kanton",
    "Kiritimati",
    "Kosrae",
    "Kwajalein",
    "Majuro",
    "Marquesas",
    "Midway",
    "Nauru",
    "Niue",
    "Norfolk",
    "Noumea",
    "Pago_Pago",
    "Palau",
    "Pitcairn",
    "Pohnpei",
    "Ponape",
    "Port_Moresby",
    "Rarotonga",
    "Saipan",
    "Samoa",
    "Tahiti",
    "Tarawa",
    "Tongatapu",
    "Truk",
    "Wake",
    "Wallis",
    "Yap"
};

static const TableValue Pacific_vals[] = {
    {true, {"<+13>-13"}},
    {true, {"NZST-12NZDT,M9.5.0,M4.1.0/3"}},
    {true, {"<+11>-11"}},
    {true, {"<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45"}},
    {true, {"<+10>-10"}},
    {true, {"<-06>6<-05>,M9.1.6/22,M4.1.6/22"}},
    {true, {"<+11>-11"}},
    {true, {"<+13>-13"}},
    {true, {"<+13>-13"}},
    {true, {"<+12>-12"}},
    {true, {"<+12>-12"}},
    {true, {"<-06>6"}},
    {true, {"<-09>9"}},
    {true, {"<+11>-11"}},
    {true, {"ChST-10"}},
    {true, {"HST10"}},
    {true, {"HST10"}},
    {true, {"<+13>-13"}},
    {true, {"<+14>-14"}},
    {true, {"<+11>-11"}},
    {true, {"<+12>-12"}},
    {true, {"<+12>-12"}},
    {true, {"<-0930>9:30"}},
    {true, {"SST11"}},
    {true, {"<+12>-12"}},
    {true, {"<-11>11"}},
    {true, {"<+11>-11<+12>,M10.1.0,M4.1.0/3"}},
    {true, {"<+11>-11"}},
    {true, {"SST11"}},
    {true, {"<+09>-9"}},
    {true, {"<-08>8"}},
    {true, {"<+11>-11"}},
    {true, {"<+11>-11"}},
    {true, {"<+10>-10"}},
    {true, {"<-10>10"}},
    {true, {"ChST-10"}},
    {true, {"SST11"}},
    {true, {"<-10>10"}},
    {true, {"<+12>-12"}},
    {true, {"<+13>-13"}},
    {true, {"<+10>-10"}},
    {true, {"<+12>-12"}},
    {true, {"<+12>-12"}},
    {true, {"<+10>-10"}},
};

static const Table Pacific = {Pacific_keys, Pacific_vals, 44};

static const char * const global_keys[] = {
    "Africa",
    "America",
    "Antarctica",
    "Arctic",
    "Asia",
    "Atlantic",
    "Australia",
    "Etc",
    "Europe",
    "Indian",
    "Pacific"
};

static const TableValue global_vals[] = {
    {false, {.sub_table=&Africa}},
    {false, {.sub_table=&America}},
    {false, {.sub_table=&Antarctica}},
    {false, {.sub_table=&Arctic}},
    {false, {.sub_table=&Asia}},
    {false, {.sub_table=&Atlantic}},
    {false, {.sub_table=&Australia}},
    {false, {.sub_table=&Etc}},
    {false, {.sub_table=&Europe}},
    {false, {.sub_table=&Indian}},
    {false, {.sub_table=&Pacific}},
};

const Table global = {global_keys, global_vals, 11};
