[Dependencies]
Requires = Task Scheduler
           Event Log
           EVSE V2
           Meters

[Options]
; the default display name has to be configured in the env
meters_evse_v2_default_display_name =
