// WARNING: This file is generated.

#pragma once

#define MODULE_ENERGY_MANAGER_AVAILABLE() 0
#define MODULE_POWER_MANAGER_AVAILABLE() 0
#define MODULE_EVSE_COMMON_AVAILABLE() 0
#define MODULE_AUTOMATION_AVAILABLE() 0
#define MODULE_FIRMWARE_UPDATE_AVAILABLE() 0
