name: WARP Charger Firmwares
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        environment: [warp3, warp2, warp]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ matrix.environment }}-${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build WARP3 Charger Firmware
        working-directory: ./software
        run: pio run -e ${{ matrix.environment }}
