name: WARP Firmwares
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        environment: [warp4, warp3, warp2, warp, energy_manager_v2, energy_manager, eltako, smart_energy_broker, esp32_ethernet, esp32]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
            ./software/.pio
            ./software/packages
          key: ${{ matrix.os }}-${{ github.run_id }}
          restore-keys: ${{ matrix.os }}-
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: 'Build Firmware: ${{ matrix.environment }}'
        working-directory: ./software
        run: pio run -e ${{ matrix.environment }} -t clean && pio run -e ${{ matrix.environment }}
      - name: 'Deleting Caches: ${{ matrix.os }}-'
        if: matrix.environment == 'warp4'
        run: gh cache delete ${{ matrix.os }}- --succeed-on-no-caches
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      - uses: actions/cache/save@v4
        if: matrix.environment == 'warp4'
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
            ./software/.pio
            ./software/packages
          key: ${{ matrix.os }}-${{ github.run_id }}
